export const ENGINE_REGISTRY_SCHEMA_VERSION = 1
export const MAINTAINER_AGENT_MANIFEST_SCHEMA_VERSION = 1
export const WORKFLOW_CANVAS_PRODUCT_VERSION = '0.1.0-alpha.0'

function deepFreeze(value, seen = new WeakSet()) {
  if (!value || typeof value !== 'object' || seen.has(value)) return value
  seen.add(value)
  for (const child of Object.values(value)) deepFreeze(child, seen)
  return Object.freeze(value)
}

const topLevel = ({ id, name, description, inputs, outputs, codeEvidence, testEvidence, compatibility, row, column, technicalVersion = '0.1.0-alpha.0' }) => ({
  id,
  name,
  kind: 'engine',
  parentId: null,
  productVersion: WORKFLOW_CANVAS_PRODUCT_VERSION,
  technicalVersion,
  maturity: 'alpha',
  maintainerAgentId: null,
  description,
  inputs,
  outputs,
  codeEvidence,
  testEvidence,
  compatibility,
  display: { row, column, order: 0 },
})

const component = ({ id, parentId, name, kind, description, inputs, outputs, codeEvidence, testEvidence, compatibility = [], order, technicalVersion = '0.1.0-alpha.0' }) => ({
  id,
  name,
  kind,
  parentId,
  productVersion: WORKFLOW_CANVAS_PRODUCT_VERSION,
  technicalVersion,
  maturity: kind === 'agent-skill' ? 'prototype' : 'alpha',
  maintainerAgentId: null,
  description,
  inputs,
  outputs,
  codeEvidence,
  testEvidence,
  compatibility,
  display: { order },
})

export const WORKFLOW_ENGINE_REGISTRY = deepFreeze({
  schemaVersion: ENGINE_REGISTRY_SCHEMA_VERSION,
  product: {
    id: 'workflow-canvas-os',
    name: 'Workflow Canvas OS',
    version: WORKFLOW_CANVAS_PRODUCT_VERSION,
    releaseStage: 'internal-alpha',
  },
  components: [
    topLevel({
      id: 'engine-twin-core',
      name: 'Asset Core',
      description: '서로 다른 시스템의 근거를 공급자 중립 Asset 원장(Asset Base)으로 정규화하고 현재 캔버스와 대조합니다.',
      inputs: ['Connector 발견 결과', '현재 캔버스', '제품·엔진 manifest'],
      outputs: ['Asset 원장의 wire 이름은 TwinBuild v3다', '검토 수정안', '논리 구성요소 지도'],
      codeEvidence: ['shared/twinBuild.js', 'shared/twinBuildReconciler.js', 'shared/twinBuildCanvas.js'],
      testEvidence: ['scripts/test-twin-build.mjs', 'scripts/test-twin-adapter-contract.mjs'],
      compatibility: ['Engine Schema v2', 'TwinBuild v3', 'Adapter Contract v1'],
      technicalVersion: '0.3.0-alpha.0',
      row: 0,
      column: 0,
    }),
    component({
      id: 'component-twin-adapter-contract',
      parentId: 'engine-twin-core',
      name: 'Twin Adapter Contract',
      kind: 'contract',
      description: '새 시스템 Adapter가 제공해야 할 발견, 권한, 대조와 조작 능력의 호환성 경계입니다. 새 이름을 만들지 않고 배포된 레거시 코드명을 유지합니다.',
      inputs: ['Adapter descriptor', 'Adapter module'],
      outputs: ['검증된 Adapter 등록'],
      codeEvidence: ['shared/twinAdapterContract.js'],
      testEvidence: ['scripts/test-twin-adapter-contract.mjs'],
      compatibility: ['Adapter Contract v1', 'Engine Schema v2'],
      order: 1,
    }),
    component({
      id: 'component-twin-builder',
      parentId: 'engine-twin-core',
      name: 'Asset Builder',
      kind: 'builder',
      description: 'Asset, 파츠, 관계, 근거, 정책과 관측을 버전이 있는 Asset 원장(Asset Base)으로 만듭니다.',
      inputs: ['정규화된 시스템 사실'],
      outputs: ['Asset 원장의 wire 이름은 TwinBuild v3다'],
      codeEvidence: ['shared/twinBuild.js'],
      testEvidence: ['scripts/test-twin-build.mjs'],
      compatibility: ['TwinBuild v3'],
      order: 2,
    }),
    component({
      id: 'component-twin-reconciler',
      parentId: 'engine-twin-core',
      name: 'Asset Reconciler',
      kind: 'pipeline',
      description: '새 Asset 원장과 현재 캔버스를 비교해 사용자 배치와 메모를 보존한 수정안을 만듭니다.',
      inputs: ['Asset 원장의 wire 이름은 TwinBuild다', '현재 캔버스'],
      outputs: ['추가·교체 수정안', '차단 사유'],
      codeEvidence: ['shared/twinBuildReconciler.js', 'shared/digitalTwinProposal.js'],
      testEvidence: ['scripts/test-twin-build.mjs'],
      compatibility: ['Reconciliation Schema v1'],
      technicalVersion: '0.3.0-alpha.0',
      order: 3,
    }),
    component({
      id: 'component-capability-mapper',
      parentId: 'engine-twin-core',
      name: 'Capability Mapper',
      kind: 'builder',
      description: '엔진 registry를 읽어 제품의 논리 엔진과 내부 구성요소를 캔버스 노드와 근거 관계로 만듭니다.',
      inputs: ['Engine registry', 'Maintainer Agent manifest'],
      outputs: ['논리 엔진 노드', '구성 관계'],
      codeEvidence: ['shared/engineRegistry.js', 'shared/capabilityMapper.js'],
      testEvidence: ['scripts/test-engine-registry.mjs'],
      compatibility: ['Engine Registry v1'],
      order: 4,
    }),

    topLevel({
      id: 'engine-create-graph',
      name: 'Draw Map',
      description: '배치·연결선·그룹만 담당하며 온톨로지·사실 판정과 무관한 순수 가시화 엔진입니다.',
      inputs: ['승인된 노드·연결선·그룹 명세', '배치 방향', '캔버스 권한'],
      outputs: ['저장된 노드·연결선', 'ID 매핑', '중복·이동 결과'],
      codeEvidence: ['mcp/server.js', 'mcp/store.js', 'mcp/layout.js'],
      testEvidence: ['scripts/test-mcp-logic.mjs'],
      compatibility: ['MCP Tool create_graph v1'],
      row: 0,
      column: 1,
    }),
    component({
      id: 'component-graph-layout',
      parentId: 'engine-create-graph',
      name: '지도 배치',
      kind: 'builder',
      description: '방향형·방사형 위치, 충돌 회피와 연결점 방향을 결정적으로 계산합니다.',
      inputs: ['노드 크기', '관계', '배치 preset'],
      outputs: ['노드 좌표', '연결점 방향'],
      codeEvidence: ['mcp/layout.js'],
      testEvidence: ['scripts/test-mcp-logic.mjs'],
      order: 1,
    }),
    component({
      id: 'component-graph-materializer',
      parentId: 'engine-create-graph',
      name: '지도 Materializer',
      kind: 'builder',
      description: '검증된 임시 ID와 관계를 실제 캔버스 노드·연결선 레코드로 변환하고 저장합니다.',
      inputs: ['검증된 지도 명세', '계산된 좌표'],
      outputs: ['실제 캔버스 레코드'],
      codeEvidence: ['mcp/store.js:createGraph'],
      testEvidence: ['scripts/test-mcp-logic.mjs'],
      order: 2,
    }),
    component({
      id: 'component-graph-composition-skill',
      parentId: 'engine-create-graph',
      name: '지도 구성 Skill',
      kind: 'agent-skill',
      description: 'AI에게 자료를 노드, 메모와 관계로 구조화하는 순서와 Draw Map의 wire 이름인 create_graph의 사용법을 안내합니다.',
      inputs: ['사용자 의도', '원문 자료'],
      outputs: ['구조화된 지도 명세'],
      codeEvidence: ['mcp/server.js'],
      testEvidence: ['scripts/test-mcp-logic.mjs'],
      order: 3,
    }),
    component({
      id: 'component-graph-write-guardrails',
      parentId: 'engine-create-graph',
      name: '지도 쓰기 Guardrails',
      kind: 'guardrail',
      description: '입력 한도, 텍스트 정제, 공유 범위 권한, 중복과 저장 충돌을 서버에서 강제합니다.',
      inputs: ['사용자·캔버스 권한', '지도 입력'],
      outputs: ['허용된 입력 또는 거부 사유'],
      codeEvidence: ['mcp/layout.js:validateGraphInput', 'mcp/shareAccess.js', 'mcp/store.js'],
      testEvidence: ['scripts/test-mcp-logic.mjs', 'scripts/test-sql-security.mjs'],
      order: 4,
    }),

    topLevel({
      id: 'engine-source-lens',
      name: 'Source Lens',
      description: '경계가 제한된 소프트웨어 소스를 하나의 결정적 분석 Workflow로 해석해 제품 의미, 코드 계층, 근거, 정적 관계, 기능 맥락과 기능 경계를 만듭니다.',
      inputs: ['경계가 제한된 Source corpus', '제품별 Source Profile', '선택적 이전 분석 결과', '선택적 이전 Functional Context Pack'],
      outputs: ['Source Analysis Bundle', 'Functional Context Pack', 'Source manifest의 wire 이름은 Source Twin 호환 형식이다', '계층형 코드 Asset 설명', '결정적 코드 파츠', '정적 관계·Flow', '기능 경계'],
      codeEvidence: ['scripts/source-lens-engine.mjs', 'scripts/source-twin-scanner.mjs', 'shared/sourceCodeParts.js', 'shared/sourceFlows.js', 'shared/sourceFunctionalContext.js', 'shared/sourceFeatureModel.js', 'shared/sourceProfileContract.js', 'shared/sourceAssetHierarchy.js'],
      testEvidence: ['scripts/test-source-lens-engine.mjs', 'scripts/test-source-functional-context.mjs', 'scripts/test-source-code-parts.mjs', 'scripts/test-source-feature-model.mjs', 'scripts/test-source-profiles.mjs', 'scripts/test-source-twin.mjs'],
      compatibility: ['Source Analysis Workflow v1.1', 'Source Analysis Contract v2', 'Functional Context Pack v1', 'Source Twin Schema v1', 'Source Profile Contract v1', 'Source Asset Hierarchy v1', 'Code Part Schema v1', 'Source Flow Schema v1'],
      technicalVersion: '0.9.0-alpha.0',
      row: 0,
      column: 2,
    }),
    component({
      id: 'component-source-analysis-contract',
      parentId: 'engine-source-lens',
      name: 'Source Analysis Contract',
      kind: 'contract',
      description: '단일 Source Analysis Workflow의 입력, 필수 Functional Context Pack, 선택 출력, 결정성과 소유 경계를 고정합니다.',
      inputs: ['Source corpus', 'Source Profile', '이전 분석 결과', '이전 Functional Context Pack', '출력 선택'],
      outputs: ['Source Analysis Bundle v2 또는 계약 오류'],
      codeEvidence: ['scripts/source-lens-engine.mjs'],
      testEvidence: ['scripts/test-source-lens-engine.mjs', 'scripts/test-source-functional-context.mjs'],
      compatibility: ['Source Analysis Workflow v1.1', 'Source Analysis Contract v2'],
      technicalVersion: '0.2.0-alpha.0',
      order: 1,
    }),
    component({
      id: 'component-source-scanner',
      parentId: 'engine-source-lens',
      name: 'Source Analysis Pipeline',
      kind: 'pipeline',
      description: 'Babel AST와 구조화된 SQL 규칙으로 파일, 함수, UI 문구·화면 경로, API, DB, 보안 신호, 코드 파츠와 정적 호출 근거를 추출하고 기능 맥락 준비 단계를 조율합니다.',
      inputs: ['허용된 저장소 파일'],
      outputs: ['본문이 제외된 코드 근거', '안정 AST 앵커', 'import·call·render 근거'],
      codeEvidence: ['scripts/source-lens-engine.mjs', 'scripts/source-twin-scanner.mjs'],
      testEvidence: ['scripts/test-source-lens-engine.mjs', 'scripts/test-source-profiles.mjs', 'scripts/test-source-twin.mjs'],
      compatibility: ['Source Analysis Workflow v1.1', 'JavaScript AST', 'SQL declaration scan', 'structure-only file discovery'],
      technicalVersion: '0.5.0-alpha.0',
      order: 2,
    }),
    component({
      id: 'component-source-corpus-guardrail',
      parentId: 'engine-source-lens',
      name: 'Source Corpus Guardrail',
      kind: 'guardrail',
      description: '허용 경로, 일반 파일, 심볼릭 링크, 파일별·전체 크기 한도를 코드에서 강제합니다.',
      inputs: ['저장소 root', '후보 상대 경로'],
      outputs: ['허용된 bounded corpus 또는 거부 사유'],
      codeEvidence: ['scripts/source-twin-scanner.mjs:readSourceTwinWorkingTree'],
      testEvidence: ['scripts/test-source-twin.mjs', 'scripts/test-source-lens-engine.mjs'],
      compatibility: ['Source Analysis Workflow v1.1'],
      order: 3,
    }),
    component({
      id: 'component-source-profile',
      parentId: 'engine-source-lens',
      name: 'Source Profile Registry',
      kind: 'manifest',
      description: '버전 계약에 따라 저장소에 맞는 제품 영역, 서브시스템과 파일 역할 사전을 선택합니다.',
      inputs: ['저장소 식별 근거', '버전이 있는 Source Profile'],
      outputs: ['선택된 프로필', '제품별 분류와 설명 규칙'],
      codeEvidence: ['shared/sourceProfileContract.js', 'scripts/source-profiles/index.mjs', 'scripts/source-profiles/workflow-canvas.mjs', 'scripts/source-profiles/fastapi-order-service.mjs'],
      testEvidence: ['scripts/test-source-profiles.mjs', 'scripts/test-source-feature-model.mjs'],
      compatibility: ['Source Profile Contract v1', 'Feature Model extension v1', 'Workflow Canvas Profile 0.9.0', 'FastAPI reference Profile 0.2.0'],
      technicalVersion: '0.4.0-alpha.0',
      order: 4,
    }),
    component({
      id: 'component-source-feature-classifier',
      parentId: 'engine-source-lens',
      name: 'Feature Boundary Resolver',
      kind: 'resolver',
      description: 'Source Profile의 결정적 3등급 규칙과 실제 코드·DB 근거를 대조해 기능 Asset, Capability와 표시하지 않을 속성을 판정합니다.',
      inputs: ['Source manifest의 wire 이름은 Source Twin이다', 'Feature Model extension v1'],
      outputs: ['근거가 연결된 기능 후보', '구현·읽기·쓰기 관계 후보', '근거 부족 진단'],
      codeEvidence: ['shared/sourceFeatureModel.js', 'shared/sourceProfileContract.js', 'shared/workflowSourceFeatureBuild.js'],
      testEvidence: ['scripts/test-source-feature-model.mjs', 'scripts/test-twin-build.mjs'],
      compatibility: ['Source Twin Schema v1', 'Source Profile Contract v1', 'Feature Model extension v1'],
      technicalVersion: '0.1.0-alpha.0',
      order: 5,
    }),
    component({
      id: 'component-source-component-mapper',
      parentId: 'engine-source-lens',
      name: 'Source Component Mapper',
      kind: 'builder',
      description: 'Registry의 코드 근거와 Source Profile 규칙만 사용해 Component와 모듈 Asset 후보의 소속을 결정합니다.',
      inputs: ['Engine Registry codeEvidence', 'Source Profile implementationRules', '소스 Asset'],
      outputs: ['Component catalog', '근거가 있는 모듈 소속'],
      codeEvidence: ['shared/sourceAssetHierarchy.js', 'shared/sourceProfileContract.js', 'scripts/source-profiles/workflow-canvas.mjs'],
      testEvidence: ['scripts/test-source-twin.mjs', 'scripts/test-source-profiles.mjs'],
      compatibility: ['Source Asset Hierarchy v1', 'Engine Registry v1'],
      technicalVersion: '0.1.0-alpha.0',
      order: 6,
    }),
    component({
      id: 'component-source-code-part-translator',
      parentId: 'engine-source-lens',
      name: 'Code Part Translator',
      kind: 'builder',
      description: 'AST 근거를 선언·명령·분기·반복·반환·리소스·설정·데이터 파츠로 분류하고 쉬운 결정적 문장과 근거 링크를 만듭니다.',
      inputs: ['Babel AST 노드', '파일·심볼·범위 근거'],
      outputs: ['읽기 전용 코드 파츠', '결정적 자연어 설명', '안정 앵커'],
      codeEvidence: ['shared/sourceCodeParts.js', 'scripts/source-twin-scanner.mjs'],
      testEvidence: ['scripts/test-source-code-parts.mjs'],
      compatibility: ['Code Part Schema v1', 'Source Twin Schema v1'],
      technicalVersion: '0.1.0-alpha.0',
      order: 7,
    }),
    component({
      id: 'component-source-flow-discovery',
      parentId: 'engine-source-lens',
      name: 'Static Flow Builder',
      kind: 'builder',
      description: 'UI 이벤트·API·MCP 진입점에서 import, 정적 호출, React render와 props 흐름을 추적하고 동적 대상은 unknown으로 남깁니다.',
      inputs: ['import binding', 'call site', 'JSX render·props', '진입점'],
      outputs: ['정적 호출 흐름', '화면 구성 흐름', 'dimmed workflow 후보', 'unknown 진단'],
      codeEvidence: ['shared/sourceFlows.js', 'scripts/source-twin-scanner.mjs'],
      testEvidence: ['scripts/test-source-code-parts.mjs'],
      compatibility: ['Source Flow Schema v1', 'CODE evidence only'],
      technicalVersion: '0.1.0-alpha.0',
      order: 8,
    }),
    component({
      id: 'component-source-functional-context-contract',
      parentId: 'engine-source-lens',
      name: 'Functional Context Contract',
      kind: 'contract',
      description: 'G10-0이 만드는 제한된 기능 어휘, 문서 최신성, 근거 참조, fingerprint와 재사용 정보의 버전형 형식을 검사합니다.',
      inputs: ['Functional Context Pack 후보'],
      outputs: ['Functional Context Pack v1 또는 계약 오류'],
      codeEvidence: ['shared/sourceFunctionalContext.js'],
      testEvidence: ['scripts/test-source-functional-context.mjs'],
      compatibility: ['Functional Context Pack v1', 'Source Analysis Contract v2'],
      order: 9,
    }),
    component({
      id: 'component-source-functional-context-resolver',
      parentId: 'engine-source-lens',
      name: 'Functional Context Resolver',
      kind: 'resolver',
      description: 'README·기획 문서의 변경 여부를 실제 소스 fingerprint와 대조하고, 문서가 없거나 오래됐을 때 UI·경로·API·DB·테스트·Flow 근거로 전환합니다.',
      inputs: ['문서 fingerprint', '현재·이전 소스 fingerprint', '소스 근거 후보'],
      outputs: ['문서 최신성 판정', '문서 검증 또는 소스 근거 fallback 전략'],
      codeEvidence: ['shared/sourceFunctionalContext.js', 'scripts/source-twin-scanner.mjs'],
      testEvidence: ['scripts/test-source-functional-context.mjs'],
      compatibility: ['Functional Context Pack v1'],
      order: 10,
    }),
    component({
      id: 'component-source-functional-context-builder',
      parentId: 'engine-source-lens',
      name: 'Functional Context Pack Builder',
      kind: 'builder',
      description: '최신 문서와 실제 소스 근거에서 기능 어휘 후보를 모아 안정 ID·근거·신뢰도·fingerprint가 있는 제한된 Pack으로 만듭니다.',
      inputs: ['최신 문서 후보', 'UI·화면 경로·API·DB·테스트·정적 Flow 근거', '이전 Functional Context Pack'],
      outputs: ['Functional Context Pack v1'],
      codeEvidence: ['shared/sourceFunctionalContext.js'],
      testEvidence: ['scripts/test-source-functional-context.mjs', 'scripts/test-source-lens-engine.mjs'],
      compatibility: ['Functional Context Pack v1'],
      order: 11,
    }),
    component({
      id: 'component-source-functional-context-guardrail',
      parentId: 'engine-source-lens',
      name: 'Functional Context Guardrail',
      kind: 'guardrail',
      description: '문서·문자·어휘·근거 수를 제한하고 AI 지휘 문서를 기능 입력에서 제외하며 비밀값처럼 보이는 문구와 오래된 문서를 기능 어휘로 사용하지 못하게 합니다.',
      inputs: ['문서·소스 기능 어휘 후보'],
      outputs: ['허용된 제한 후보 또는 명시적 진단'],
      codeEvidence: ['shared/sourceFunctionalContext.js'],
      testEvidence: ['scripts/test-source-functional-context.mjs'],
      compatibility: ['Functional Context Pack v1'],
      order: 12,
    }),

    topLevel({
      id: 'engine-trust-map',
      name: 'Trust Map',
      description: '로컬, 클라우드와 외부 SaaS의 신뢰 구역, 게이트웨이와 확인되지 않은 통로를 판정하고 redaction 이후 지도에 시각화합니다.',
      inputs: ['Asset 신뢰 구역', '관계 게이트웨이', '데이터 종류'],
      outputs: ['경계 분석', 'unknown gap', 'redaction 안전 보안 오버레이', '위협·통제 연결'],
      codeEvidence: ['shared/trustTopology.js', 'shared/securityOverlay.js', 'shared/twinBuild.js'],
      testEvidence: ['scripts/test-security-overlay.mjs', 'scripts/test-twin-build.mjs', 'scripts/test-twin-adapter-contract.mjs'],
      compatibility: ['Trust Topology Schema v1', 'Security Overlay Schema v1'],
      technicalVersion: '0.2.0-alpha.0',
      row: 1,
      column: 0,
    }),
    component({
      id: 'component-trust-contract',
      parentId: 'engine-trust-map',
      name: 'Trust Topology Contract',
      kind: 'contract',
      description: '신뢰 구역과 경계를 지나는 게이트웨이의 공통 필드를 검증합니다.',
      inputs: ['Zone·Gateway 선언'],
      outputs: ['정규화된 Trust Topology'],
      codeEvidence: ['shared/trustTopology.js'],
      testEvidence: ['scripts/test-twin-build.mjs'],
      compatibility: ['Trust Topology Schema v1'],
      order: 1,
    }),
    component({
      id: 'component-trust-boundary-resolver',
      parentId: 'engine-trust-map',
      name: 'Trust Boundary Resolver',
      kind: 'resolver',
      description: '서로 다른 구역의 관계가 명시된 게이트웨이를 지나는지 검사하고 빈 통로를 찾습니다.',
      inputs: ['Source·Target zone', '관계 Gateway'],
      outputs: ['same-zone·modeled-crossing·unknown-gap'],
      codeEvidence: ['shared/trustTopology.js:analyzeTrustBoundary'],
      testEvidence: ['scripts/test-twin-build.mjs'],
      order: 2,
    }),
    component({
      id: 'component-trust-overlay-projector',
      parentId: 'engine-trust-map',
      name: 'Security Overlay Projector',
      kind: 'builder',
      description: '보는 사람에게 허용된 노드와 연결선만 사용해 신뢰영역 색, 게이트웨이와 unknown-gap 표시를 만듭니다.',
      inputs: ['redaction 이후 캔버스 지도', 'Trust Topology 선언'],
      outputs: ['노드 신뢰영역 표시', '게이트웨이 상세', 'unknown-gap 경고'],
      codeEvidence: ['shared/securityOverlay.js', 'src/nodes/SystemNode.jsx', 'src/edges/StubEdge.jsx'],
      testEvidence: ['scripts/test-security-overlay.mjs'],
      compatibility: ['Trust Topology Schema v1', 'Security Overlay Schema v1'],
      order: 3,
    }),

    topLevel({
      id: 'engine-liveops',
      name: 'LiveOps',
      description: '허용된 운영 정보를 확인하고 관측 시각, 신선도와 LIVE·stale 상태를 판정합니다.',
      inputs: ['운영 확인 요청', '허용된 공급자 응답'],
      outputs: ['정제된 관측', '신선도·검증 수준'],
      codeEvidence: ['shared/systemRuntime.js', 'mcp/systemRuntime.js', 'api/system-runtime.js'],
      testEvidence: ['scripts/test-mcp-logic.mjs'],
      compatibility: ['System Runtime Schema v3'],
      row: 1,
      column: 1,
    }),
    component({
      id: 'component-runtime-contract',
      parentId: 'engine-liveops',
      name: 'Runtime Contract',
      kind: 'contract',
      description: '운영 확인 요청, 결과 종류, 관측 시각과 신선도 판정 형식을 정의합니다.',
      inputs: ['Capability 요청', '관측 결과'],
      outputs: ['정규화된 Runtime 결과'],
      codeEvidence: ['shared/systemRuntime.js'],
      testEvidence: ['scripts/test-mcp-logic.mjs'],
      compatibility: ['System Runtime Schema v3'],
      order: 1,
    }),
    component({
      id: 'component-runtime-observation-pipeline',
      parentId: 'engine-liveops',
      name: 'Runtime Observation Pipeline',
      kind: 'pipeline',
      description: 'Vercel, Supabase, API와 MCP의 허용된 상태만 조회하고 민감한 값을 제거합니다.',
      inputs: ['Allowlisted capability'],
      outputs: ['저장 가능한 운영 관측'],
      codeEvidence: ['mcp/systemRuntime.js', 'api/system-runtime.js'],
      testEvidence: ['scripts/test-mcp-logic.mjs'],
      order: 2,
    }),

    topLevel({
      id: 'engine-safe-operations',
      name: 'Safe Operations',
      description: '직접 클릭, 자동화와 미래 AI 조작을 같은 계획, 승인, 실행, 검증, 감사와 복구 과정으로 제한하고 등록된 소스 편집도 이 경계에서 다룹니다.',
      inputs: ['조작 의도', '권한·위험 정책', '현재 상태'],
      outputs: ['서명 계획', '검증된 결과', '감사 사건'],
      codeEvidence: ['shared/operationLifecycle.js', 'shared/workflowOperationDefinitions.js', 'shared/systemStateSnapshot.js', 'mcp/systemOperationPlan.js'],
      testEvidence: ['scripts/test-operation-lifecycle.mjs', 'scripts/test-source-editable-properties.mjs', 'scripts/test-local-connector-agent.mjs'],
      compatibility: ['Operation Contract v1', 'Editable Property Schema v1'],
      technicalVersion: '0.2.0-alpha.0',
      row: 1,
      column: 2,
    }),
    component({
      id: 'component-operation-lifecycle',
      parentId: 'engine-safe-operations',
      name: 'Operation Lifecycle',
      kind: 'pipeline',
      description: '조작 실행의 상태 전이, 승인, 검증, 재시도와 복구 규칙을 결정적으로 검사합니다.',
      inputs: ['Operation definition', 'Plan·Run event'],
      outputs: ['유효한 다음 상태', '감사 사건'],
      codeEvidence: ['shared/operationLifecycle.js'],
      testEvidence: ['scripts/test-operation-lifecycle.mjs'],
      compatibility: ['Operation Contract v1'],
      order: 1,
    }),
    component({
      id: 'component-operation-definitions',
      parentId: 'engine-safe-operations',
      name: 'Operation Definitions',
      kind: 'manifest',
      description: 'Git 동기화, 시스템 상태 스냅샷과 등록 소스 편집의 대상, 위험, 검증과 복구 조건을 선언합니다.',
      inputs: ['제품별 조작 요구'],
      outputs: ['검증된 Operation definition'],
      codeEvidence: ['shared/workflowOperationDefinitions.js', 'shared/systemStateSnapshot.js'],
      testEvidence: ['scripts/test-operation-lifecycle.mjs'],
      order: 2,
    }),
    component({
      id: 'component-source-roundtrip-editor',
      parentId: 'engine-safe-operations',
      name: 'Source Edit Pipeline',
      kind: 'pipeline',
      description: '등록된 UI literal 하나를 서명 계획, 이중 승인, 격리 검증과 복구 가능한 commit/revert 절차로 제한합니다.',
      inputs: ['Editable Property Schema v1', 'Source Lens 안정 AST 앵커', '소유자 승인', '로컬 터미널 승인'],
      outputs: ['검증된 편집 결과', 'diff 지문', '복구 가능한 감사 결과'],
      codeEvidence: ['shared/sourceEditableProperties.js', 'shared/workflowSourceEditableProperties.js', 'shared/workflowSourceEditCodePartAdapter.js', 'scripts/source-edit-executor.mjs', 'mcp/localConnectorStore.js'],
      testEvidence: ['scripts/test-source-editable-properties.mjs', 'scripts/test-local-connector-agent.mjs'],
      compatibility: ['Operation Contract v1', 'Editable Property Schema v1', 'Local Connector Agent 1.3'],
      technicalVersion: '0.2.0-alpha.0',
      order: 3,
    }),

    topLevel({
      id: 'engine-work-core',
      name: 'Work Core',
      description: '투입, 처리와 결과를 가진 Work 계약을 만들고 버전이 고정된 Intent 조문을 Work에 조립합니다. 현재는 실행기가 아니라 실행 전 구조와 통제 조건을 관리합니다.',
      inputs: ['Work 파츠 입력', '기록된 Intent 버전', '편집 권한'],
      outputs: ['정규화된 Work 계약', '버전 고정 Intent 장착 정보', '실행 전 검증 오류'],
      codeEvidence: ['shared/workOntology.js', 'shared/systemPartOntology.js', 'src/nodes/SystemNode.jsx'],
      testEvidence: ['scripts/test-work-intent-parts.mjs'],
      compatibility: ['Work Schema v1', 'System Part Contract v1', 'Intent Schema v1'],
      technicalVersion: '0.1.0-alpha.0',
      row: 2,
      column: 1,
    }),
    component({
      id: 'component-work-part-contract',
      parentId: 'engine-work-core',
      name: 'Work Part Contract',
      kind: 'contract',
      description: 'Work에 투입, 처리, 결과를 필수로 요구하고 일반 파츠가 Work나 Intent 데이터를 가장하지 못하게 정규화합니다.',
      inputs: ['시스템 파츠 입력'],
      outputs: ['검증된 Work 파츠 또는 거부 사유'],
      codeEvidence: ['shared/workOntology.js', 'shared/systemPartOntology.js'],
      testEvidence: ['scripts/test-work-intent-parts.mjs'],
      compatibility: ['Work Schema v1', 'System Part Contract v1'],
      order: 1,
    }),
    component({
      id: 'component-work-intent-assembly',
      parentId: 'engine-work-core',
      name: 'Work Intent Assembly',
      kind: 'resolver',
      description: '기록된 Intent 버전을 Work에 여러 개 장착하고 원본 변경과 무관하게 선택한 버전을 고정합니다.',
      inputs: ['Work 파츠', '기록된 Intent 선택 정보'],
      outputs: ['중복 제거된 Intent 장착 목록', '누락·업데이트 표시'],
      codeEvidence: ['shared/workOntology.js', 'src/components/WorkIntentPicker.jsx', 'src/nodes/SystemNode.jsx'],
      testEvidence: ['scripts/test-work-intent-parts.mjs'],
      compatibility: ['Work Schema v1', 'Intent Schema v1'],
      order: 2,
    }),

    topLevel({
      id: 'engine-intent-core',
      name: 'Intent Engine',
      description: '회의, AI 대화와 문서 원문을 근거와 함께 보존하고 조문 후보를 만들어 사람의 승인 후 버전 자산으로 고정합니다. 현재 추출은 결정적 초안 생성이며 AI 하네스 집행은 포함하지 않습니다.',
      inputs: ['Intent 요약', '회의·AI 대화·문서 원문', '사람의 조문 승인'],
      outputs: ['근거가 연결된 조문 후보', '확정 조문', '버전이 기록된 Intent 자산'],
      codeEvidence: ['shared/intentOntology.js', 'src/components/IntentWorkspace.jsx', 'src/nodes/IntentNode.jsx'],
      testEvidence: ['scripts/test-intent-node.mjs', 'scripts/test-work-intent-parts.mjs'],
      compatibility: ['Intent Schema v1', 'Work Schema v1'],
      technicalVersion: '0.2.0-alpha.0',
      row: 2,
      column: 2,
    }),
    component({
      id: 'component-intent-asset-contract',
      parentId: 'engine-intent-core',
      name: 'Intent Asset Contract',
      kind: 'contract',
      description: 'Intent의 원문, 조문, 상태와 변경 불가능한 버전 스냅샷 형식을 정규화합니다.',
      inputs: ['Intent 편집 내용', '원문과 조문'],
      outputs: ['정규화된 Intent 자산', '기록 버전'],
      codeEvidence: ['shared/intentOntology.js'],
      testEvidence: ['scripts/test-intent-node.mjs'],
      compatibility: ['Intent Schema v1'],
      order: 1,
    }),
    component({
      id: 'component-intent-clause-extractor',
      parentId: 'engine-intent-core',
      name: 'Intent Clause Extractor',
      kind: 'resolver',
      description: '원문 문장을 분리하고 준수, 금지, 목적과 성공 기준 등의 조문 후보로 분류하며 원문 근거를 함께 남깁니다. 후보를 자동 확정하지 않습니다.',
      inputs: ['원문 또는 Intent 요약'],
      outputs: ['근거 포함 조문 후보'],
      codeEvidence: ['shared/intentOntology.js:extractIntentClauseCandidates', 'src/components/IntentWorkspace.jsx'],
      testEvidence: ['scripts/test-intent-node.mjs'],
      compatibility: ['Intent Schema v1', 'Deterministic Extractor v1'],
      technicalVersion: '0.1.0-alpha.0',
      order: 2,
    }),
    component({
      id: 'component-intent-work-resolver',
      parentId: 'engine-intent-core',
      name: 'Intent Work Resolver',
      kind: 'resolver',
      description: 'Work 선택기에 노출할 최소 Intent 정보와 기록 버전을 계산하고 원문 자료는 실행 인터페이스와 MCP에서 분리합니다.',
      inputs: ['Intent 자산', '최신 기록 버전'],
      outputs: ['Work 선택 정보', '버전 고정 장착 참조'],
      codeEvidence: ['shared/workOntology.js', 'mcp/store.js'],
      testEvidence: ['scripts/test-intent-node.mjs', 'scripts/test-work-intent-parts.mjs'],
      compatibility: ['Intent Schema v1', 'Work Schema v1'],
      order: 3,
    }),

    topLevel({
      id: 'engine-connector-bridge',
      name: 'Connector Bridge',
      description: '외부 시스템, 로컬 저장소와 선택적 AI 제공자의 형식을 Asset Core와 Safe Operations 계약으로 변환합니다.',
      inputs: ['외부 API·로컬 저장소 상태', '최소 권한 grant', '승인된 제공자 설정'],
      outputs: ['정규화된 발견 결과', '제한 조작 결과', '출처가 표시된 외부 설명'],
      codeEvidence: ['shared/twinAdapterContract.js', 'scripts/local-connector-agent.mjs', 'shared/workflowSystemTwinAdapter.js', 'shared/sourceAiExplanation.js'],
      testEvidence: ['scripts/test-twin-adapter-contract.mjs', 'scripts/test-local-connector-agent.mjs', 'scripts/test-source-code-parts.mjs'],
      compatibility: ['Adapter Contract v1', 'Local Connector Schema v1', 'Provider-neutral AI adapter'],
      technicalVersion: '0.2.0-alpha.0',
      row: 2,
      column: 0,
    }),
    component({
      id: 'component-workflow-twin-adapter',
      parentId: 'engine-connector-bridge',
      name: 'Workflow Twin Adapter',
      kind: 'connector',
      description: 'Workflow Canvas 전용 시스템 발견 결과를 Asset 원장과 수정안으로 변환합니다. 새 이름을 만들지 않고 배포된 레거시 코드명을 유지합니다.',
      inputs: ['Workflow 시스템 manifest', '현재 시스템 지도'],
      outputs: ['Workflow Asset 원장의 wire 이름은 Workflow TwinBuild다', '검토 항목'],
      codeEvidence: ['shared/workflowSystemTwinAdapter.js', 'shared/workflowSystemTwinBuild.js'],
      testEvidence: ['scripts/test-twin-adapter-contract.mjs'],
      compatibility: ['Adapter Contract v1'],
      order: 1,
    }),
    component({
      id: 'component-local-connector',
      parentId: 'engine-connector-bridge',
      name: 'Local Connector',
      kind: 'connector',
      description: '사용자가 허용한 로컬 Git 저장소를 읽고, 승인된 비강제 동기화와 별도 쓰기 동의를 받은 등록 UI 속성 편집·롤백만 수행합니다.',
      inputs: ['선택한 저장소 grant', '승인된 조작 계획', '별도 소스 쓰기 동의'],
      outputs: ['본문 제외 Source manifest', '검증된 Git 결과', '검증된 provenance 편집·revert 커밋'],
      codeEvidence: ['scripts/local-connector-agent.mjs', 'shared/localConnector.js', 'api/local-connector.js'],
      testEvidence: ['scripts/test-local-connector-agent.mjs'],
      compatibility: ['Local Connector Agent v1.3.0', 'Schema v1', 'Editable Property Schema v1'],
      technicalVersion: '1.3.0',
      order: 2,
    }),
    component({
      id: 'component-source-ai-explanation',
      parentId: 'engine-connector-bridge',
      name: 'External AI Explanation Connector',
      kind: 'connector',
      description: '소유자 자기 지도에서만 결정적 설명과 외부 AI 문장 품질을 비교하며 관계·권한·Reality를 만들지 않습니다.',
      inputs: ['코드 파츠 종류', '심볼', '상대 경로·줄 범위', '결정적 요약', '승인된 제공자 설정'],
      outputs: ['AI 생성 출처가 표시된 보강 문장'],
      codeEvidence: ['shared/sourceAiExplanation.js', 'api/source-twin.js'],
      testEvidence: ['scripts/test-source-code-parts.mjs'],
      compatibility: ['Provider-neutral adapter', 'owner-only disabled-by-default pilot'],
      technicalVersion: '0.2.0-alpha.0',
      order: 3,
    }),

    topLevel({
      id: 'engine-ai-context-gate',
      name: 'AI Context Gate',
      description: '개발을 맡은 상대 AI에게 사용자가 소유하는 단 하나의 Project Master 유지 규칙을 전달하고, 전달 확인과 실제 완료 차단 수준을 구별하는 Starting Protocol의 직접 참여 엔진입니다.',
      inputs: ['프로젝트 상태 기준 fingerprint', '상대 AI 전달 능력', '선택된 기획 사실', '선택적 기존 Project Master'],
      outputs: ['AI Context Enrollment Manifest', '토큰 제한 기획 기록 프롬프트', 'PROJECT_MASTER.md 휴대형 제안', '강제 수준', '검증된 Handoff Receipt'],
      codeEvidence: ['scripts/ai-context-gate-engine.mjs', 'shared/aiContextGate.js'],
      testEvidence: ['scripts/test-ai-context-gate.mjs'],
      compatibility: ['Project Master Enrollment Workflow v1', 'AI Context Gate Contract v1'],
      technicalVersion: '0.1.0-alpha.0',
      row: 3,
      column: 0,
    }),
    component({
      id: 'component-ai-context-contract',
      parentId: 'engine-ai-context-gate',
      name: 'AI Context Contract',
      kind: 'contract',
      description: '프로젝트 기준점, 대상 AI, Project Master, 전달 방식, 토큰 예산과 Handoff Receipt의 버전 경계를 고정합니다.',
      inputs: ['프로젝트 식별자', '프로젝트 상태·Project Master 기준 fingerprint', '전달 설정'],
      outputs: ['검증된 Enrollment 입력 또는 계약 오류'],
      codeEvidence: ['shared/aiContextGate.js', 'scripts/ai-context-gate-engine.mjs'],
      testEvidence: ['scripts/test-ai-context-gate.mjs'],
      compatibility: ['AI Context Gate Contract v1'],
      order: 1,
    }),
    component({
      id: 'component-ai-delivery-resolver',
      parentId: 'engine-ai-context-gate',
      name: 'AI Delivery Resolver',
      kind: 'resolver',
      description: '수동 프롬프트, Connector 전달, 제품이 통제하는 개발 완료 경계를 구분하고 실제 증거보다 강한 강제 수준을 주장하지 않습니다.',
      inputs: ['전달 방식', '전달 Receipt', '완료 Gate 결합 증거', '신뢰된 Host 검증기'],
      outputs: ['권고·전달 검증·완료 차단 판정', 'Connector Exchange 요청'],
      codeEvidence: ['shared/aiContextGate.js'],
      testEvidence: ['scripts/test-ai-context-gate.mjs'],
      compatibility: ['AI Context Gate Contract v1', 'Connector Bridge handoff'],
      order: 2,
    }),
    component({
      id: 'component-project-master-builder',
      parentId: 'engine-ai-context-gate',
      name: 'Project Master Builder',
      kind: 'builder',
      description: '호스트가 고른 필요한 기획 사실만 예산 안에서 정규화해 상대 AI용 기록 프롬프트와 사용자가 소유하는 단일 Project Master 틀을 만듭니다.',
      inputs: ['검증된 프로젝트 정보', '선택된 기획 사실', 'Project Master 경로'],
      outputs: ['버전이 고정된 프롬프트', 'PROJECT_MASTER.md 휴대형 제안'],
      codeEvidence: ['shared/aiContextGate.js'],
      testEvidence: ['scripts/test-ai-context-gate.mjs'],
      compatibility: ['Project Master Enrollment Workflow v1'],
      order: 3,
    }),
    component({
      id: 'component-project-master-handoff-pipeline',
      parentId: 'engine-ai-context-gate',
      name: 'Project Master Handoff Pipeline',
      kind: 'pipeline',
      description: '기준점을 묶은 Enrollment를 만들고 개발 완료 시 기획 변경 선언, 근거와 Project Master 변경을 대조해 Receipt를 발급합니다.',
      inputs: ['Enrollment 입력', '상대 AI 완료 선언', '호스트가 관측한 fingerprint와 변경 신호'],
      outputs: ['Enrollment Manifest', '검증된 Handoff Receipt 또는 차단 사유'],
      codeEvidence: ['scripts/ai-context-gate-engine.mjs', 'shared/aiContextGate.js'],
      testEvidence: ['scripts/test-ai-context-gate.mjs'],
      compatibility: ['Project Master Enrollment Workflow v1'],
      order: 4,
    }),
    component({
      id: 'component-project-master-recording-skill',
      parentId: 'engine-ai-context-gate',
      name: 'Project Master Recording Skill',
      kind: 'agent-skill',
      description: '상대 AI에게 프로젝트 목적·사용자·범위·기능·흐름·제약·결정·미확인을 단일 기획 정본에 짧게 유지하는 절차를 제공합니다.',
      inputs: ['기획에 영향을 주는 개발 작업', '제한된 기획 Context Pack', '사용자 결정·문서·코드 근거'],
      outputs: ['Project Master 갱신 제안', 'planning 또는 none 완료 선언'],
      codeEvidence: ['shared/aiContextGate.js:buildTargetAiPrompt'],
      testEvidence: ['scripts/test-ai-context-gate.mjs'],
      compatibility: ['AI Context Gate Prompt v1'],
      order: 5,
    }),
    component({
      id: 'component-project-master-evidence-policy',
      parentId: 'engine-ai-context-gate',
      name: 'Project Master Evidence Policy',
      kind: 'agent-policy',
      description: '사용자 확정 기획을 조용히 덮어쓰지 않고 AI 제안을 분리하며, 근거가 낮거나 충돌하는 내용은 Project Master의 미확인으로 남기게 합니다.',
      inputs: ['사용자 확정 기획', 'AI 제안', '사용자 결정·문서·코드 근거'],
      outputs: ['확정·제안·미확인으로 구분된 단일 Project Master'],
      codeEvidence: ['shared/aiContextGate.js:buildTargetAiPrompt', 'shared/aiContextGate.js:buildProjectMasterTemplate'],
      testEvidence: ['scripts/test-ai-context-gate.mjs'],
      compatibility: ['AI Context Gate Prompt v1'],
      order: 6,
    }),
    component({
      id: 'component-project-master-guardrail',
      parentId: 'engine-ai-context-gate',
      name: 'Project Master Guardrail',
      kind: 'guardrail',
      description: '상대 경로, 입력 크기, 토큰 예산, 기준 fingerprint, 기획 변경 시 Project Master 갱신과 완료 Gate 결합을 코드에서 검증합니다.',
      inputs: ['프롬프트·기획 입력', '관측된 완료 상태'],
      outputs: ['허용된 Enrollment·Receipt 또는 명시적 거부'],
      codeEvidence: ['shared/aiContextGate.js'],
      testEvidence: ['scripts/test-ai-context-gate.mjs'],
      compatibility: ['AI Context Gate Contract v1'],
      order: 7,
    }),
    component({
      id: 'component-ai-context-enrollment-manifest',
      parentId: 'engine-ai-context-gate',
      name: 'AI Context Enrollment Manifest',
      kind: 'manifest',
      description: '어떤 프롬프트와 Project Master 기준점이 어떤 전달 방식·강제 수준에 묶였는지를 결정적 fingerprint로 기록합니다.',
      inputs: ['정규화된 Enrollment 사실'],
      outputs: ['fingerprint가 결합된 Enrollment Manifest'],
      codeEvidence: ['shared/aiContextGate.js:createAiContextEnrollment'],
      testEvidence: ['scripts/test-ai-context-gate.mjs'],
      compatibility: ['AI Context Gate Contract v1'],
      order: 8,
    }),
  ],
})

// A Maintainer Agent is not assigned yet. This planned bundle-level profile
// records the minimum contract that a future agent must satisfy before it can
// be attached to any engine in the registry.
export const MAINTAINER_AGENT_MANIFEST = deepFreeze({
  schemaVersion: MAINTAINER_AGENT_MANIFEST_SCHEMA_VERSION,
  agents: [{
    id: 'agent-core-engine-maintainer',
    name: 'Core Engine Maintainer',
    status: 'planned-unassigned',
    scope: {
      engineIds: WORKFLOW_ENGINE_REGISTRY.components
        .filter((item) => item.kind === 'engine' && !item.parentId)
        .map((item) => item.id),
      responsibilities: ['호환성 검토', '수정안 작성', '테스트 근거 수집', 'changelog 제안'],
      excluded: ['프로덕션 직접 변경', '사용자 데이터 열람', '비밀값 접근', '승인 없는 의존성 도입'],
    },
    allowedTools: ['repository-read', 'test-runner', 'build-runner', 'patch-proposal'],
    requiredTests: ['npm test', 'npm run build'],
    escalation: ['호환성 깨짐', 'DB·권한·암호화 변경', '새 외부 의존성', '운영 데이터 쓰기', '배포'],
    humanApprovalRequiredFor: ['코드 적용', '스키마 변경', '의존성 채택', '보안 정책 변경', '커밋·푸시·배포'],
  }],
})
