export const ENGINE_REGISTRY_SCHEMA_VERSION = 1
export const MAINTAINER_AGENT_MANIFEST_SCHEMA_VERSION = 1
export const WORKFLOW_CANVAS_PRODUCT_VERSION = '0.1.0-alpha.0'

function deepFreeze(value, seen = new WeakSet()) {
  if (!value || typeof value !== 'object' || seen.has(value)) return value
  seen.add(value)
  for (const child of Object.values(value)) deepFreeze(child, seen)
  return Object.freeze(value)
}

const topLevel = ({ id, name, description, inputs, outputs, codeEvidence, testEvidence, compatibility, row, column, technicalVersion = '0.1.0-alpha.0' }) => ({
  id,
  name,
  kind: 'engine',
  parentId: null,
  productVersion: WORKFLOW_CANVAS_PRODUCT_VERSION,
  technicalVersion,
  maturity: 'alpha',
  maintainerAgentId: null,
  description,
  inputs,
  outputs,
  codeEvidence,
  testEvidence,
  compatibility,
  display: { row, column, order: 0 },
})

const component = ({ id, parentId, name, kind, description, inputs, outputs, codeEvidence, testEvidence, compatibility = [], order, technicalVersion = '0.1.0-alpha.0' }) => ({
  id,
  name,
  kind,
  parentId,
  productVersion: WORKFLOW_CANVAS_PRODUCT_VERSION,
  technicalVersion,
  maturity: kind === 'agent-skill' ? 'prototype' : 'alpha',
  maintainerAgentId: null,
  description,
  inputs,
  outputs,
  codeEvidence,
  testEvidence,
  compatibility,
  display: { order },
})

export const WORKFLOW_ENGINE_REGISTRY = deepFreeze({
  schemaVersion: ENGINE_REGISTRY_SCHEMA_VERSION,
  product: {
    id: 'workflow-canvas-os',
    name: 'Workflow Canvas OS',
    version: WORKFLOW_CANVAS_PRODUCT_VERSION,
    releaseStage: 'internal-alpha',
  },
  components: [
    topLevel({
      id: 'engine-twin-core',
      name: 'Twin Core',
      description: '서로 다른 시스템의 근거를 공급자 중립 디지털 트윈으로 정규화하고 현재 캔버스와 대조합니다.',
      inputs: ['Connector 발견 결과', '현재 캔버스', '제품·엔진 manifest'],
      outputs: ['Canonical TwinBuild', '검토 수정안', '논리 구성요소 지도'],
      codeEvidence: ['shared/twinBuild.js', 'shared/twinBuildReconciler.js', 'shared/twinBuildCanvas.js'],
      testEvidence: ['scripts/test-twin-build.mjs', 'scripts/test-twin-adapter-contract.mjs'],
      compatibility: ['Engine Schema v2', 'TwinBuild v3', 'Adapter Contract v1'],
      technicalVersion: '0.2.0-alpha.0',
      row: 0,
      column: 0,
    }),
    component({
      id: 'component-twin-adapter-contract',
      parentId: 'engine-twin-core',
      name: 'Twin Adapter Contract',
      kind: 'contract',
      description: '새 시스템 Connector가 제공해야 할 발견, 권한, 대조와 조작 능력의 호환성 경계입니다.',
      inputs: ['Adapter descriptor', 'Adapter module'],
      outputs: ['검증된 Adapter 등록'],
      codeEvidence: ['shared/twinAdapterContract.js'],
      testEvidence: ['scripts/test-twin-adapter-contract.mjs'],
      compatibility: ['Adapter Contract v1', 'Engine Schema v2'],
      order: 1,
    }),
    component({
      id: 'component-twin-builder',
      parentId: 'engine-twin-core',
      name: 'Twin Builder',
      kind: 'builder',
      description: '엔티티, 파츠, 관계, 근거, 정책과 관측을 버전이 있는 Canonical TwinBuild로 만듭니다.',
      inputs: ['정규화된 시스템 사실'],
      outputs: ['TwinBuild v3'],
      codeEvidence: ['shared/twinBuild.js'],
      testEvidence: ['scripts/test-twin-build.mjs'],
      compatibility: ['TwinBuild v3'],
      order: 2,
    }),
    component({
      id: 'component-twin-reconciler',
      parentId: 'engine-twin-core',
      name: 'Twin Reconciler',
      kind: 'pipeline',
      description: '새 TwinBuild와 현재 캔버스를 비교해 사용자 배치와 메모를 보존한 수정안을 만듭니다.',
      inputs: ['TwinBuild', '현재 캔버스'],
      outputs: ['추가·교체 수정안', '차단 사유'],
      codeEvidence: ['shared/twinBuildReconciler.js', 'shared/digitalTwinProposal.js'],
      testEvidence: ['scripts/test-twin-build.mjs'],
      compatibility: ['Reconciliation Schema v1'],
      technicalVersion: '0.2.0-alpha.0',
      order: 3,
    }),
    component({
      id: 'component-capability-mapper',
      parentId: 'engine-twin-core',
      name: 'Capability Mapper',
      kind: 'builder',
      description: '엔진 registry를 읽어 제품의 논리 엔진과 내부 구성요소를 캔버스 노드와 근거 관계로 만듭니다.',
      inputs: ['Engine registry', 'Maintainer Agent manifest'],
      outputs: ['논리 엔진 노드', '구성 관계'],
      codeEvidence: ['shared/engineRegistry.js', 'shared/capabilityMapper.js'],
      testEvidence: ['scripts/test-engine-registry.mjs'],
      compatibility: ['Engine Registry v1'],
      order: 4,
    }),

    topLevel({
      id: 'engine-create-graph',
      name: 'Create Graph',
      description: '구조화된 노드와 관계 요청을 검증하고 배치해 실제 캔버스 그래프로 저장합니다.',
      inputs: ['노드·관계 명세', '레이아웃 방향', '캔버스 권한'],
      outputs: ['저장된 노드·연결선', 'ID 매핑', '중복·이동 결과'],
      codeEvidence: ['mcp/server.js', 'mcp/store.js', 'mcp/layout.js'],
      testEvidence: ['scripts/test-mcp-logic.mjs'],
      compatibility: ['MCP Tool create_graph v1'],
      row: 0,
      column: 1,
    }),
    component({
      id: 'component-graph-layout',
      parentId: 'engine-create-graph',
      name: 'Graph Layout',
      kind: 'engine',
      description: '방향형·방사형 위치, 충돌 회피와 연결점 방향을 결정적으로 계산합니다.',
      inputs: ['노드 크기', '관계', '배치 preset'],
      outputs: ['노드 좌표', '연결점 방향'],
      codeEvidence: ['mcp/layout.js'],
      testEvidence: ['scripts/test-mcp-logic.mjs'],
      order: 1,
    }),
    component({
      id: 'component-graph-materializer',
      parentId: 'engine-create-graph',
      name: 'Graph Materializer',
      kind: 'builder',
      description: '검증된 임시 ID와 관계를 실제 캔버스 노드·연결선 레코드로 변환하고 저장합니다.',
      inputs: ['검증된 그래프 명세', '계산된 좌표'],
      outputs: ['실제 캔버스 레코드'],
      codeEvidence: ['mcp/store.js:createGraph'],
      testEvidence: ['scripts/test-mcp-logic.mjs'],
      order: 2,
    }),
    component({
      id: 'component-graph-composition-skill',
      parentId: 'engine-create-graph',
      name: 'Graph Composition Skill',
      kind: 'agent-skill',
      description: 'AI에게 자료를 노드, 메모와 관계로 구조화하는 순서와 create_graph 사용법을 안내합니다.',
      inputs: ['사용자 의도', '원문 자료'],
      outputs: ['구조화된 그래프 명세'],
      codeEvidence: ['mcp/server.js'],
      testEvidence: ['scripts/test-mcp-logic.mjs'],
      order: 3,
    }),
    component({
      id: 'component-graph-write-guardrails',
      parentId: 'engine-create-graph',
      name: 'Graph Write Guardrails',
      kind: 'guardrail',
      description: '입력 한도, 텍스트 정제, 공유 범위 권한, 중복과 저장 충돌을 서버에서 강제합니다.',
      inputs: ['사용자·캔버스 권한', '그래프 입력'],
      outputs: ['허용된 입력 또는 거부 사유'],
      codeEvidence: ['mcp/layout.js:validateGraphInput', 'mcp/shareAccess.js', 'mcp/store.js'],
      testEvidence: ['scripts/test-mcp-logic.mjs', 'scripts/test-sql-security.mjs'],
      order: 4,
    }),

    topLevel({
      id: 'engine-source-lens',
      name: 'Source Lens',
      description: '코드를 제품 영역과 하위 시스템으로 묶고 쉬운 설명과 개발자 근거를 함께 만듭니다.',
      inputs: ['Git 저장소 파일', '제품별 Source Profile'],
      outputs: ['Source Twin manifest', '계층형 코드 설명'],
      codeEvidence: ['scripts/source-twin-scanner.mjs', 'scripts/source-twin-semantics.mjs', 'shared/sourceProfileContract.js', 'shared/sourceTwin.js'],
      testEvidence: ['scripts/test-source-profiles.mjs', 'scripts/test-source-twin.mjs', 'scripts/test-local-connector-agent.mjs'],
      compatibility: ['Source Twin Schema v1', 'Source Profile Contract v1'],
      technicalVersion: '0.2.0-alpha.0',
      row: 0,
      column: 2,
    }),
    component({
      id: 'component-source-scanner',
      parentId: 'engine-source-lens',
      name: 'Source Scanner',
      kind: 'engine',
      description: 'Babel AST와 구조화된 SQL 규칙으로 파일, 함수, API, DB와 보안 신호를 추출합니다.',
      inputs: ['허용된 저장소 파일'],
      outputs: ['본문이 제외된 코드 근거'],
      codeEvidence: ['scripts/source-twin-scanner.mjs'],
      testEvidence: ['scripts/test-source-profiles.mjs', 'scripts/test-source-twin.mjs'],
      compatibility: ['JavaScript AST', 'SQL declaration scan', 'structure-only file discovery'],
      technicalVersion: '0.2.0-alpha.0',
      order: 1,
    }),
    component({
      id: 'component-source-profile',
      parentId: 'engine-source-lens',
      name: 'Source Profile Registry',
      kind: 'manifest',
      description: '버전 계약에 따라 저장소에 맞는 제품 영역, 하위 시스템과 파일 역할 사전을 선택합니다.',
      inputs: ['저장소 식별 근거', '버전이 있는 Source Profile'],
      outputs: ['선택된 프로필', '제품별 분류와 설명 규칙'],
      codeEvidence: ['shared/sourceProfileContract.js', 'scripts/source-profiles/index.mjs', 'scripts/source-profiles/workflow-canvas.mjs', 'scripts/source-profiles/fastapi-order-service.mjs'],
      testEvidence: ['scripts/test-source-profiles.mjs'],
      compatibility: ['Source Profile Contract v1', 'Workflow Canvas Profile 0.1.0', 'FastAPI reference Profile 0.1.0'],
      technicalVersion: '0.2.0-alpha.0',
      order: 2,
    }),

    topLevel({
      id: 'engine-trust-map',
      name: 'Trust Map',
      description: '로컬, 클라우드와 외부 SaaS의 신뢰 구역, 게이트웨이와 확인되지 않은 통로를 판정합니다.',
      inputs: ['엔티티 신뢰 구역', '관계 게이트웨이', '데이터 종류'],
      outputs: ['경계 분석', 'unknown gap', '위협·통제 연결'],
      codeEvidence: ['shared/trustTopology.js', 'shared/twinBuild.js'],
      testEvidence: ['scripts/test-twin-build.mjs', 'scripts/test-twin-adapter-contract.mjs'],
      compatibility: ['Trust Topology Schema v1'],
      row: 1,
      column: 0,
    }),
    component({
      id: 'component-trust-contract',
      parentId: 'engine-trust-map',
      name: 'Trust Topology Contract',
      kind: 'contract',
      description: '신뢰 구역과 경계를 지나는 게이트웨이의 공통 필드를 검증합니다.',
      inputs: ['Zone·Gateway 선언'],
      outputs: ['정규화된 Trust Topology'],
      codeEvidence: ['shared/trustTopology.js'],
      testEvidence: ['scripts/test-twin-build.mjs'],
      compatibility: ['Trust Topology Schema v1'],
      order: 1,
    }),
    component({
      id: 'component-trust-boundary-resolver',
      parentId: 'engine-trust-map',
      name: 'Trust Boundary Resolver',
      kind: 'resolver',
      description: '서로 다른 구역의 관계가 명시된 게이트웨이를 지나는지 검사하고 빈 통로를 찾습니다.',
      inputs: ['Source·Target zone', '관계 Gateway'],
      outputs: ['same-zone·modeled-crossing·unknown-gap'],
      codeEvidence: ['shared/trustTopology.js:analyzeTrustBoundary'],
      testEvidence: ['scripts/test-twin-build.mjs'],
      order: 2,
    }),

    topLevel({
      id: 'engine-liveops',
      name: 'LiveOps',
      description: '허용된 운영 정보를 확인하고 관측 시각, 신선도와 LIVE·stale 상태를 판정합니다.',
      inputs: ['운영 확인 요청', '허용된 공급자 응답'],
      outputs: ['정제된 관측', '신선도·검증 수준'],
      codeEvidence: ['shared/systemRuntime.js', 'mcp/systemRuntime.js', 'api/system-runtime.js'],
      testEvidence: ['scripts/test-mcp-logic.mjs'],
      compatibility: ['System Runtime Schema v3'],
      row: 1,
      column: 1,
    }),
    component({
      id: 'component-runtime-contract',
      parentId: 'engine-liveops',
      name: 'Runtime Contract',
      kind: 'contract',
      description: '운영 확인 요청, 결과 종류, 관측 시각과 신선도 판정 형식을 정의합니다.',
      inputs: ['Capability 요청', '관측 결과'],
      outputs: ['정규화된 Runtime 결과'],
      codeEvidence: ['shared/systemRuntime.js'],
      testEvidence: ['scripts/test-mcp-logic.mjs'],
      compatibility: ['System Runtime Schema v3'],
      order: 1,
    }),
    component({
      id: 'component-runtime-observation-pipeline',
      parentId: 'engine-liveops',
      name: 'Runtime Observation Pipeline',
      kind: 'pipeline',
      description: 'Vercel, Supabase, API와 MCP의 허용된 상태만 조회하고 민감한 값을 제거합니다.',
      inputs: ['Allowlisted capability'],
      outputs: ['저장 가능한 운영 관측'],
      codeEvidence: ['mcp/systemRuntime.js', 'api/system-runtime.js'],
      testEvidence: ['scripts/test-mcp-logic.mjs'],
      order: 2,
    }),

    topLevel({
      id: 'engine-safe-operations',
      name: 'Safe Operations',
      description: '직접 클릭, 자동화와 미래 AI 조작을 같은 계획, 승인, 실행, 검증, 감사와 복구 과정으로 제한합니다.',
      inputs: ['조작 의도', '권한·위험 정책', '현재 상태'],
      outputs: ['서명 계획', '검증된 결과', '감사 사건'],
      codeEvidence: ['shared/operationLifecycle.js', 'shared/workflowOperationDefinitions.js', 'mcp/systemOperationPlan.js'],
      testEvidence: ['scripts/test-operation-lifecycle.mjs', 'scripts/test-local-connector-agent.mjs'],
      compatibility: ['Operation Contract v1'],
      row: 1,
      column: 2,
    }),
    component({
      id: 'component-operation-lifecycle',
      parentId: 'engine-safe-operations',
      name: 'Operation Lifecycle',
      kind: 'engine',
      description: '조작 실행의 상태 전이, 승인, 검증, 재시도와 복구 규칙을 결정적으로 검사합니다.',
      inputs: ['Operation definition', 'Plan·Run event'],
      outputs: ['유효한 다음 상태', '감사 사건'],
      codeEvidence: ['shared/operationLifecycle.js'],
      testEvidence: ['scripts/test-operation-lifecycle.mjs'],
      compatibility: ['Operation Contract v1'],
      order: 1,
    }),
    component({
      id: 'component-operation-definitions',
      parentId: 'engine-safe-operations',
      name: 'Operation Definitions',
      kind: 'manifest',
      description: 'Git 동기화와 시스템 스냅샷의 대상, 위험, 검증과 복구 조건을 선언합니다.',
      inputs: ['제품별 조작 요구'],
      outputs: ['검증된 Operation definition'],
      codeEvidence: ['shared/workflowOperationDefinitions.js'],
      testEvidence: ['scripts/test-operation-lifecycle.mjs'],
      order: 2,
    }),

    topLevel({
      id: 'engine-connector-bridge',
      name: 'Connector Bridge',
      description: '외부 시스템과 로컬 저장소의 형식을 Twin Core와 Safe Operations 계약으로 변환합니다.',
      inputs: ['외부 API·로컬 저장소 상태', '최소 권한 grant'],
      outputs: ['정규화된 발견 결과', '제한 조작 결과'],
      codeEvidence: ['shared/twinAdapterContract.js', 'scripts/local-connector-agent.mjs', 'shared/workflowSystemTwinAdapter.js'],
      testEvidence: ['scripts/test-twin-adapter-contract.mjs', 'scripts/test-local-connector-agent.mjs'],
      compatibility: ['Adapter Contract v1', 'Local Connector Schema v1'],
      row: 2,
      column: 0,
    }),
    component({
      id: 'component-workflow-twin-adapter',
      parentId: 'engine-connector-bridge',
      name: 'Workflow Twin Adapter',
      kind: 'connector',
      description: 'Workflow Canvas 전용 시스템 발견 결과를 공통 TwinBuild와 수정안으로 변환합니다.',
      inputs: ['Workflow 시스템 manifest', '현재 시스템 지도'],
      outputs: ['Workflow TwinBuild', '검토 항목'],
      codeEvidence: ['shared/workflowSystemTwinAdapter.js', 'shared/workflowSystemTwinBuild.js'],
      testEvidence: ['scripts/test-twin-adapter-contract.mjs'],
      compatibility: ['Adapter Contract v1'],
      order: 1,
    }),
    component({
      id: 'component-local-connector',
      parentId: 'engine-connector-bridge',
      name: 'Local Connector',
      kind: 'connector',
      description: '사용자가 허용한 로컬 Git 저장소를 읽고 승인된 비강제 동기화만 수행합니다.',
      inputs: ['선택한 저장소 grant', '승인된 조작 계획'],
      outputs: ['본문 제외 Source manifest', '검증된 Git 결과'],
      codeEvidence: ['scripts/local-connector-agent.mjs', 'shared/localConnector.js', 'api/local-connector.js'],
      testEvidence: ['scripts/test-local-connector-agent.mjs'],
      compatibility: ['Local Connector Agent v1.2.0', 'Schema v1'],
      order: 2,
    }),
  ],
})

// A Maintainer Agent is not assigned yet. This planned bundle-level profile
// records the minimum contract that a future agent must satisfy before it can
// be attached to any engine in the registry.
export const MAINTAINER_AGENT_MANIFEST = deepFreeze({
  schemaVersion: MAINTAINER_AGENT_MANIFEST_SCHEMA_VERSION,
  agents: [{
    id: 'agent-core-engine-maintainer',
    name: 'Core Engine Maintainer',
    status: 'planned-unassigned',
    scope: {
      engineIds: WORKFLOW_ENGINE_REGISTRY.components
        .filter((item) => item.kind === 'engine' && !item.parentId)
        .map((item) => item.id),
      responsibilities: ['호환성 검토', '수정안 작성', '테스트 근거 수집', 'changelog 제안'],
      excluded: ['프로덕션 직접 변경', '사용자 데이터 열람', '비밀값 접근', '승인 없는 의존성 도입'],
    },
    allowedTools: ['repository-read', 'test-runner', 'build-runner', 'patch-proposal'],
    requiredTests: ['npm test', 'npm run build'],
    escalation: ['호환성 깨짐', 'DB·권한·암호화 변경', '새 외부 의존성', '운영 데이터 쓰기', '배포'],
    humanApprovalRequiredFor: ['코드 적용', '스키마 변경', '의존성 채택', '보안 정책 변경', '커밋·푸시·배포'],
  }],
})
