// Generated by scripts/generate-source-twin.mjs. Do not edit by hand.
export const SOURCE_FUNCTIONAL_CONTEXT_MANIFEST = Object.freeze(
{
  "schemaVersion": 1,
  "type": "FunctionalContextPack",
  "strategy": "documents-with-source-validation",
  "source": {
    "id": "workflow-canvas:self-source",
    "profileId": "workflow-canvas",
    "profileVersion": "0.9.0"
  },
  "sourceEvidenceFingerprint": "8898d6c2b2a8aa9c",
  "documentFingerprint": "0ca632e25bc95ffa",
  "documents": [
    {
      "path": "README.md",
      "kind": "readme",
      "fingerprint": "56c9ce351ea7f8ed",
      "freshness": "possibly-stale",
      "extractedTerms": 16,
      "used": false
    },
    {
      "path": "docs/MASTER.md",
      "kind": "planning",
      "fingerprint": "72fdb69e70ba18be",
      "freshness": "changed",
      "extractedTerms": 16,
      "used": true
    },
    {
      "path": "docs/README.md",
      "kind": "readme",
      "fingerprint": "ef75168c0fa91df6",
      "freshness": "possibly-stale",
      "extractedTerms": 17,
      "used": false
    },
    {
      "path": "docs/product/PRODUCT_CATALOG.md",
      "kind": "planning",
      "fingerprint": "b45ced52a7e5788f",
      "freshness": "possibly-stale",
      "extractedTerms": 16,
      "used": false
    },
    {
      "path": "docs/twin/README.md",
      "kind": "readme",
      "fingerprint": "421e082734e5b453",
      "freshness": "possibly-stale",
      "extractedTerms": 18,
      "used": false
    }
  ],
  "vocabulary": [
    {
      "id": "functional-context:84f694c0635afbd2",
      "label": "2.1 Asset 문법 (모델 계층)",
      "normalized": "2 1 asset 문법 모델 계층",
      "confidence": "medium",
      "verification": "document-evidence",
      "sourceKinds": [
        "document-heading"
      ],
      "evidence": [
        {
          "ref": "source:docs/MASTER.md#L47",
          "kind": "document-heading",
          "fingerprint": "72fdb69e70ba18be"
        }
      ],
      "evidenceFingerprint": "dde5067ff18798f9",
      "reusedFromPrevious": false
    },
    {
      "id": "functional-context:a4426467a2d38b21",
      "label": "AI",
      "normalized": "ai",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "ui-text"
      ],
      "evidence": [
        {
          "ref": "source:src/components/SourceTwinPanel.jsx#L331",
          "kind": "ui-text",
          "fingerprint": "9c48cae2b232cc030120"
        }
      ],
      "evidenceFingerprint": "8263c1abee944ae3",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:d527504167f47bba",
      "label": "AI·MCP 연결",
      "normalized": "ai mcp 연결",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-area",
        "ui-text"
      ],
      "evidence": [
        {
          "ref": "source:api/mcp.js#L1",
          "kind": "feature-model",
          "fingerprint": "c588a33164526c123310"
        },
        {
          "ref": "source:mcp/canvasSummaries.js#L1",
          "kind": "feature-model",
          "fingerprint": "11cc15cb55600a30dc1a"
        },
        {
          "ref": "source:mcp/server.js#L1",
          "kind": "feature-model",
          "fingerprint": "deb95826cdc4a3933b59"
        },
        {
          "ref": "source:mcp/store.js#L1",
          "kind": "feature-model",
          "fingerprint": "ef8151ab288f29a35434"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-area",
          "fingerprint": "0.9.0"
        },
        {
          "ref": "source:src/components/AuthPanel.jsx#L414",
          "kind": "ui-text",
          "fingerprint": "3e41821672f8346cba65"
        }
      ],
      "evidenceFingerprint": "01a85566cdbced49",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:a67f74e99f0914e0",
      "label": "AI 문장은 근거·관계·Reality Level을 만들지 않습니다",
      "normalized": "ai 문장은 근거 관계 reality level을 만들지 않습니다",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "ui-text"
      ],
      "evidence": [
        {
          "ref": "source:src/components/SourceTwinPanel.jsx#L326",
          "kind": "ui-text",
          "fingerprint": "9c48cae2b232cc030120"
        }
      ],
      "evidenceFingerprint": "f863e25b70831721",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:a78410f9cc9cd238",
      "label": "AI 비교",
      "normalized": "ai 비교",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "ui-text"
      ],
      "evidence": [
        {
          "ref": "source:src/components/SourceTwinPanel.jsx#L279",
          "kind": "ui-text",
          "fingerprint": "9c48cae2b232cc030120"
        },
        {
          "ref": "source:src/components/SourceTwinPanel.jsx#L280",
          "kind": "ui-text",
          "fingerprint": "9c48cae2b232cc030120"
        },
        {
          "ref": "source:src/components/SourceTwinPanel.jsx#L325",
          "kind": "ui-text",
          "fingerprint": "9c48cae2b232cc030120"
        }
      ],
      "evidenceFingerprint": "a71ea87ec279cfd7",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:c7045363d715452c",
      "label": "AI 생성",
      "normalized": "ai 생성",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "ui-text"
      ],
      "evidence": [
        {
          "ref": "source:src/components/SourceTwinPanel.jsx#L329",
          "kind": "ui-text",
          "fingerprint": "9c48cae2b232cc030120"
        }
      ],
      "evidenceFingerprint": "fdf3dbd05a4f6f02",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:a737fd4ca5f26c4b",
      "label": "AI 제공자 공식 정책",
      "normalized": "ai 제공자 공식 정책",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "ui-text"
      ],
      "evidence": [
        {
          "ref": "source:src/components/SourceTwinPanel.jsx#L336",
          "kind": "ui-text",
          "fingerprint": "9c48cae2b232cc030120"
        }
      ],
      "evidenceFingerprint": "0222a858bc85d310",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:7dba1a414ead17a0",
      "label": "AI 캔버스 도구",
      "normalized": "ai 캔버스 도구",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "source:mcp/canvasSummaries.js#L1",
          "kind": "feature-model",
          "fingerprint": "11cc15cb55600a30dc1a"
        },
        {
          "ref": "source:mcp/store.js#L1",
          "kind": "feature-model",
          "fingerprint": "ef8151ab288f29a35434"
        },
        {
          "ref": "source:mcp/workshopStore.js#L1",
          "kind": "feature-model",
          "fingerprint": "05756feaf5e337f07588"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "a4a5e3636ea1313a",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:a2f7d11f5b21ef2b",
      "label": "API",
      "normalized": "api",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "ui-text"
      ],
      "evidence": [
        {
          "ref": "source:src/components/SourceTwinPanel.jsx#L348",
          "kind": "ui-text",
          "fingerprint": "9c48cae2b232cc030120"
        }
      ],
      "evidenceFingerprint": "567ef613d3d83e25",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:96688df413d7bc0f",
      "label": "api-route",
      "normalized": "api route",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "ui-text"
      ],
      "evidence": [
        {
          "ref": "source:src/components/SourceTwinPanel.jsx#L348",
          "kind": "ui-text",
          "fingerprint": "9c48cae2b232cc030120"
        }
      ],
      "evidenceFingerprint": "567ef613d3d83e25",
      "reusedFromPrevious": false
    },
    {
      "id": "functional-context:d7243ae39abd8974",
      "label": "archived",
      "normalized": "archived",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "ui-text"
      ],
      "evidence": [
        {
          "ref": "source:src/components/WorkshopBoard.jsx#L630",
          "kind": "ui-text",
          "fingerprint": "5db83bf520ace8d567ce"
        },
        {
          "ref": "source:src/components/WorkshopBoard.jsx#L632",
          "kind": "ui-text",
          "fingerprint": "5db83bf520ace8d567ce"
        }
      ],
      "evidenceFingerprint": "774370e356a3f098",
      "reusedFromPrevious": false
    },
    {
      "id": "functional-context:89273288ac6a96e2",
      "label": "Asset Core",
      "normalized": "asset core",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "a5fbd7742403ede9",
      "reusedFromPrevious": false
    },
    {
      "id": "functional-context:b1e7b94ceb6dcc78",
      "label": "Asset 원장 엔진",
      "normalized": "asset 원장 엔진",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-area",
        "profile-subsystem",
        "ui-text"
      ],
      "evidence": [
        {
          "ref": "source:api/system-runtime.js#L1",
          "kind": "feature-model",
          "fingerprint": "12a90375f6edf6d12ecd"
        },
        {
          "ref": "source:mcp/systemRuntime.js#L1",
          "kind": "feature-model",
          "fingerprint": "86c8f476d528d0166305"
        },
        {
          "ref": "source:scripts/generate-system-discovery.mjs#L1",
          "kind": "feature-model",
          "fingerprint": "749c18860105893730a3"
        },
        {
          "ref": "source:scripts/system-discovery.mjs#L1",
          "kind": "feature-model",
          "fingerprint": "b40e6bc252a510412650"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-area",
          "fingerprint": "0.9.0"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "30743a184dcc0eea",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:30da1f6407a53f88",
      "label": "Asset 원장 엔진 검사",
      "normalized": "asset 원장 엔진 검사",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-area",
        "profile-subsystem",
        "ui-text"
      ],
      "evidence": [
        {
          "ref": "source:api/system-runtime.js#L1",
          "kind": "feature-model",
          "fingerprint": "12a90375f6edf6d12ecd"
        },
        {
          "ref": "source:mcp/systemRuntime.js#L1",
          "kind": "feature-model",
          "fingerprint": "86c8f476d528d0166305"
        },
        {
          "ref": "source:scripts/generate-system-discovery.mjs#L1",
          "kind": "feature-model",
          "fingerprint": "749c18860105893730a3"
        },
        {
          "ref": "source:scripts/system-discovery.mjs#L1",
          "kind": "feature-model",
          "fingerprint": "b40e6bc252a510412650"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-area",
          "fingerprint": "0.9.0"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "30743a184dcc0eea",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:8f109685743c0ece",
      "label": "Draw Map",
      "normalized": "draw map",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "source:shared/twinBuildCanvas.js#L1",
          "kind": "feature-model",
          "fingerprint": "679a9a5768fe97b009cf"
        },
        {
          "ref": "source:shared/workflowCanvasSystemMap.js#L1",
          "kind": "feature-model",
          "fingerprint": "516094710e5ab23ea768"
        },
        {
          "ref": "source:shared/workflowSystemMapRepair.js#L1",
          "kind": "feature-model",
          "fingerprint": "ea4c480dd004984cb87a"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "21b2afcd1e3636db",
      "reusedFromPrevious": false
    },
    {
      "id": "functional-context:053ae2fc0b738451",
      "label": "Git 변경·전달",
      "normalized": "git 변경 전달",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-subsystem",
        "ui-text"
      ],
      "evidence": [
        {
          "ref": "source:api/source-twin-webhook.js#L1",
          "kind": "feature-model",
          "fingerprint": "ba21d0160c29a0d98a9b"
        },
        {
          "ref": "source:shared/workflowSourceTwinCanvas.js#L1",
          "kind": "feature-model",
          "fingerprint": "655c7a317512cd60f576"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        },
        {
          "ref": "source:src/components/CodeWorldScreen.jsx#L267",
          "kind": "ui-text",
          "fingerprint": "63f8108a21f06d48f0dd"
        }
      ],
      "evidenceFingerprint": "8ecf99170ff56de2",
      "reusedFromPrevious": false
    },
    {
      "id": "functional-context:1caafa9293cb2cfd",
      "label": "MCP 연결·인증",
      "normalized": "mcp 연결 인증",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-subsystem",
        "ui-text"
      ],
      "evidence": [
        {
          "ref": "source:api/mcp.js#L1",
          "kind": "feature-model",
          "fingerprint": "c588a33164526c123310"
        },
        {
          "ref": "source:mcp/server.js#L1",
          "kind": "feature-model",
          "fingerprint": "deb95826cdc4a3933b59"
        },
        {
          "ref": "source:src/lib/mcpTokens.js#L1",
          "kind": "feature-model",
          "fingerprint": "4ea1e5d844d29eb77d29"
        },
        {
          "ref": "source:supabase-mcp-schema.sql#L1",
          "kind": "feature-model",
          "fingerprint": "78ed8e9f3ab86e4cc230"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        },
        {
          "ref": "source:src/components/AuthPanel.jsx#L414",
          "kind": "ui-text",
          "fingerprint": "3e41821672f8346cba65"
        }
      ],
      "evidenceFingerprint": "198eb298e4a0390c",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:5a21dba052252960",
      "label": "Work·Intent 엔진",
      "normalized": "work intent 엔진",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "source:shared/intentOntology.js#L1",
          "kind": "feature-model",
          "fingerprint": "798069692801239bf29f"
        },
        {
          "ref": "source:shared/workOntology.js#L1",
          "kind": "feature-model",
          "fingerprint": "ae78251be71b9cdd8592"
        },
        {
          "ref": "source:src/components/IntentWorkspace.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "6fb49a06a307edbbaa39"
        },
        {
          "ref": "source:src/components/WorkIntentPicker.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "62ccb5251881fede50ce"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "4be67eb270aa81ac",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:89b553d08a0f69d9",
      "label": "Workflow Canvas OS 마스터 문서",
      "normalized": "workflow canvas os 마스터 문서",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "document-heading",
        "ui-text"
      ],
      "evidence": [
        {
          "ref": "source:docs/MASTER.md#L1",
          "kind": "document-heading",
          "fingerprint": "72fdb69e70ba18be"
        },
        {
          "ref": "source:src/components/SourceTwinPanel.jsx#L824",
          "kind": "ui-text",
          "fingerprint": "9c48cae2b232cc030120"
        }
      ],
      "evidenceFingerprint": "9bbdc04a0d4ef4fb",
      "reusedFromPrevious": false
    },
    {
      "id": "functional-context:68ac62d9c0d8f3a1",
      "label": "Workflow Canvas 어댑터",
      "normalized": "workflow canvas 어댑터",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "profile-subsystem",
        "ui-text"
      ],
      "evidence": [
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        },
        {
          "ref": "source:src/components/SourceTwinPanel.jsx#L824",
          "kind": "ui-text",
          "fingerprint": "9c48cae2b232cc030120"
        }
      ],
      "evidenceFingerprint": "b6ada2354b6ee88f",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:c97b7c64979c83d8",
      "label": "계정·프로필",
      "normalized": "계정 프로필",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "source:src/components/AuthPanel.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "3e41821672f8346cba65"
        },
        {
          "ref": "source:src/lib/profiles.js#L1",
          "kind": "feature-model",
          "fingerprint": "c40ac0b0effac431c97d"
        },
        {
          "ref": "source:supabase-profiles.sql#L1",
          "kind": "feature-model",
          "fingerprint": "46b9d7a755b61d38a9a6"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "d766d9fd5448cc61",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:00b93ddc97aebacf",
      "label": "공유 권한 집행",
      "normalized": "공유 권한 집행",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "source:mcp/shareAccess.js#L1",
          "kind": "feature-model",
          "fingerprint": "b6d1d0b6cb8193dc13e8"
        },
        {
          "ref": "source:shared/aiContextGate.js#L1",
          "kind": "feature-model",
          "fingerprint": "b03fc3077c717278489b"
        },
        {
          "ref": "source:shared/richTextSanitizer.js#L1",
          "kind": "feature-model",
          "fingerprint": "078919aaf8b49844f52a"
        },
        {
          "ref": "source:shared/securityOverlay.js#L1",
          "kind": "feature-model",
          "fingerprint": "2d1ec75cb05960f0c9e7"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "ef283459c2d858a0",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:f2ebf3208d00723f",
      "label": "공유·협업",
      "normalized": "공유 협업",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-area"
      ],
      "evidence": [
        {
          "ref": "source:api/shared-canvas.js#L1",
          "kind": "feature-model",
          "fingerprint": "8ac0ed036a110f045ee7"
        },
        {
          "ref": "source:mcp/shareAccess.js#L1",
          "kind": "feature-model",
          "fingerprint": "b6d1d0b6cb8193dc13e8"
        },
        {
          "ref": "source:shared/aiContextGate.js#L1",
          "kind": "feature-model",
          "fingerprint": "b03fc3077c717278489b"
        },
        {
          "ref": "source:shared/richTextSanitizer.js#L1",
          "kind": "feature-model",
          "fingerprint": "078919aaf8b49844f52a"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-area",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "676f473b70f581d9",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:224813ebef2add00",
      "label": "노드·연결선 표현",
      "normalized": "노드 연결선 표현",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "source:src/components/EdgeRelationEditor.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "dbb0f9b5387be396ff0f"
        },
        {
          "ref": "source:src/edges/StubEdge.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "71485fe4b33fafd66ce2"
        },
        {
          "ref": "source:src/lib/wheelRouting.js#L1",
          "kind": "feature-model",
          "fingerprint": "678eb0ba20d614ee7834"
        },
        {
          "ref": "source:src/nodes/GroupNode.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "228d194960d333c238cd"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "320bdd58fa7ec8e9",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:6f1956747df16fe7",
      "label": "노트 작업 공간",
      "normalized": "노트 작업 공간",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "source:src/components/NotesPanel.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "db6c9d2fba031720cce7"
        },
        {
          "ref": "source:src/components/OpenInNotesButton.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "1266b6c60659430cafa0"
        },
        {
          "ref": "source:supabase-canvas-notes.sql#L1",
          "kind": "feature-model",
          "fingerprint": "1f0adb5a842f4e24a492"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "8117d9dfc24444a4",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:38b114b5bbf2f64d",
      "label": "노트·콘텐츠",
      "normalized": "노트 콘텐츠",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-area",
        "ui-text"
      ],
      "evidence": [
        {
          "ref": "source:src/components/EditToolbar.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "bcd3449c19903c18a0ac"
        },
        {
          "ref": "source:src/components/NotesPanel.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "db6c9d2fba031720cce7"
        },
        {
          "ref": "source:src/components/OpenInNotesButton.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "1266b6c60659430cafa0"
        },
        {
          "ref": "source:src/nodes/ContentNode.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "2adf4346171b7f573854"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-area",
          "fingerprint": "0.9.0"
        },
        {
          "ref": "source:src/App.jsx#L5055",
          "kind": "ui-text",
          "fingerprint": "e1b307140827f26542aa"
        }
      ],
      "evidenceFingerprint": "25d370998417d4de",
      "reusedFromPrevious": false
    },
    {
      "id": "functional-context:552b4d05f48db0f1",
      "label": "데이터 저장·실시간 동기화",
      "normalized": "데이터 저장 실시간 동기화",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "profile-area",
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-area",
          "fingerprint": "0.9.0"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "55ea9b0d11f554f2",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:7f3fd55752cae5ac",
      "label": "데이터베이스 구조",
      "normalized": "데이터베이스 구조",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "a5fbd7742403ede9",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:f28e9677b8ee684b",
      "label": "로그인·프로필",
      "normalized": "로그인 프로필",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-area"
      ],
      "evidence": [
        {
          "ref": "source:src/components/AuthPanel.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "3e41821672f8346cba65"
        },
        {
          "ref": "source:src/lib/profiles.js#L1",
          "kind": "feature-model",
          "fingerprint": "c40ac0b0effac431c97d"
        },
        {
          "ref": "source:supabase-profiles.sql#L1",
          "kind": "feature-model",
          "fingerprint": "46b9d7a755b61d38a9a6"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-area",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "d8176a554b87e34d",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:ce3e5c32f02aba58",
      "label": "로컬 커넥터",
      "normalized": "로컬 커넥터",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-subsystem",
        "ui-text"
      ],
      "evidence": [
        {
          "ref": "source:api/local-connector.js#L1",
          "kind": "feature-model",
          "fingerprint": "8a8a2aef1fdc5fc57642"
        },
        {
          "ref": "source:mcp/localConnectorStore.js#L1",
          "kind": "feature-model",
          "fingerprint": "3615bf005d9857342fe8"
        },
        {
          "ref": "source:scripts/local-connector-agent.mjs#L1",
          "kind": "feature-model",
          "fingerprint": "e66969f8f39b22ddd049"
        },
        {
          "ref": "source:shared/localConnector.js#L1",
          "kind": "feature-model",
          "fingerprint": "358eb2c3812306db44a0"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        },
        {
          "ref": "source:src/components/SourceTwinPanel.jsx#L798",
          "kind": "ui-text",
          "fingerprint": "9c48cae2b232cc030120"
        }
      ],
      "evidenceFingerprint": "ab9c93ff617a6dac",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:ed648442922581e7",
      "label": "배포·운영",
      "normalized": "배포 운영",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "profile-area"
      ],
      "evidence": [
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-area",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "6b9004bada23f364",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:cf31598cc4bbec47",
      "label": "변경 대조·검토",
      "normalized": "변경 대조 검토",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-subsystem",
        "ui-text"
      ],
      "evidence": [
        {
          "ref": "source:shared/digitalTwinProposal.js#L1",
          "kind": "feature-model",
          "fingerprint": "c93bf4fa215796debc8f"
        },
        {
          "ref": "source:shared/digitalTwinReview.js#L1",
          "kind": "feature-model",
          "fingerprint": "c69d1bab7ae5c4e13152"
        },
        {
          "ref": "source:shared/twinBuildReconciler.js#L1",
          "kind": "feature-model",
          "fingerprint": "ffd56851ca2255798d5b"
        },
        {
          "ref": "source:src/components/DigitalTwinReviewPanel.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "8f1ad75bdc15437c98ac"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        },
        {
          "ref": "source:src/components/DigitalTwinReviewPanel.jsx#L253",
          "kind": "ui-text",
          "fingerprint": "8f1ad75bdc15437c98ac"
        }
      ],
      "evidenceFingerprint": "c15c4f22633b9ef3",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:70477b64b4a41300",
      "label": "보안·개인정보",
      "normalized": "보안 개인정보",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "profile-area"
      ],
      "evidence": [
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-area",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "6b9004bada23f364",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:ab70ca8fb701d616",
      "label": "본문·서식 편집",
      "normalized": "본문 서식 편집",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "source:src/components/EditToolbar.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "bcd3449c19903c18a0ac"
        },
        {
          "ref": "source:src/nodes/ContentNode.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "2adf4346171b7f573854"
        },
        {
          "ref": "source:src/nodes/MemoNode.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "eaeef519cd8e984351b0"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "db228429d474dce2",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:78d277b6fb434434",
      "label": "브라우저 저장",
      "normalized": "브라우저 저장",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "a5fbd7742403ede9",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:3a81b363ddae95c8",
      "label": "빌드·배포",
      "normalized": "빌드 배포",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "a5fbd7742403ede9",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:c64b009a670083cf",
      "label": "설계·운영 문서",
      "normalized": "설계 운영 문서",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "a5fbd7742403ede9",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:e32b073038cbd9a8",
      "label": "시스템 발견·정규화",
      "normalized": "시스템 발견 정규화",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "source:scripts/generate-system-discovery.mjs#L1",
          "kind": "feature-model",
          "fingerprint": "749c18860105893730a3"
        },
        {
          "ref": "source:scripts/system-discovery.mjs#L1",
          "kind": "feature-model",
          "fingerprint": "b40e6bc252a510412650"
        },
        {
          "ref": "source:shared/workflowSystemDiscovery.js#L1",
          "kind": "feature-model",
          "fingerprint": "c91651c8fe35abf847ca"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "ced0c424ffdca5cd",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:d94e91e1d2f60843",
      "label": "신뢰 경계·보호 규칙",
      "normalized": "신뢰 경계 보호 규칙",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "a5fbd7742403ede9",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:b2711bf332591d55",
      "label": "앱 기능·보안 검사",
      "normalized": "앱 기능 보안 검사",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "a5fbd7742403ede9",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:4ef11bd0cadf3597",
      "label": "운영 상태 관측",
      "normalized": "운영 상태 관측",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "source:api/system-runtime.js#L1",
          "kind": "feature-model",
          "fingerprint": "12a90375f6edf6d12ecd"
        },
        {
          "ref": "source:mcp/systemRuntime.js#L1",
          "kind": "feature-model",
          "fingerprint": "86c8f476d528d0166305"
        },
        {
          "ref": "source:shared/systemObservationCatalog.js#L1",
          "kind": "feature-model",
          "fingerprint": "79b6a6a3fb37be957250"
        },
        {
          "ref": "source:shared/systemRuntime.js#L1",
          "kind": "feature-model",
          "fingerprint": "b5974a3ccf1f8681e34f"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "e6e2955933ace749",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:dec92e01784e8b99",
      "label": "이미지·파일",
      "normalized": "이미지 파일",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-area"
      ],
      "evidence": [
        {
          "ref": "source:src/components/CanvasImage.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "874e5b725e30f30873e8"
        },
        {
          "ref": "source:src/lib/imageStorage.js#L1",
          "kind": "feature-model",
          "fingerprint": "4c4da9626df402b048a8"
        },
        {
          "ref": "source:supabase-canvas-images.sql#L1",
          "kind": "feature-model",
          "fingerprint": "d9aafbd8cf7754ce4455"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-area",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "b4ee93b8a8f1c4af",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:37c46a71b7c54dc9",
      "label": "이미지 표시",
      "normalized": "이미지 표시",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "source:src/components/CanvasImage.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "874e5b725e30f30873e8"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "bc674ebf58386a27",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:429099c18efa6ec0",
      "label": "입력·콘텐츠 안전",
      "normalized": "입력 콘텐츠 안전",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "a5fbd7742403ede9",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:4700dff15a0a78e5",
      "label": "접근 감사·개인정보",
      "normalized": "접근 감사 개인정보",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "a5fbd7742403ede9",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:d1e4884befefc6bf",
      "label": "제품·엔진 레지스트리",
      "normalized": "제품 엔진 레지스트리",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "a5fbd7742403ede9",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:ad66c87a0b5e8a78",
      "label": "조작·검증 수명주기",
      "normalized": "조작 검증 수명주기",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "source:shared/edgeOperation.js#L1",
          "kind": "feature-model",
          "fingerprint": "184557badd9774b09415"
        },
        {
          "ref": "source:shared/operationLifecycle.js#L1",
          "kind": "feature-model",
          "fingerprint": "545ebee0a269773760ea"
        },
        {
          "ref": "source:shared/workflowOperationDefinitions.js#L1",
          "kind": "feature-model",
          "fingerprint": "694a2fae63884c756813"
        },
        {
          "ref": "source:shared/workflowSourceEditCodePartAdapter.js#L1",
          "kind": "feature-model",
          "fingerprint": "db311afc6c9583ee901e"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "066ccad44c41a68d",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:b9b91d1f57a11330",
      "label": "중심 문장",
      "normalized": "중심 문장",
      "confidence": "medium",
      "verification": "document-evidence",
      "sourceKinds": [
        "document-heading"
      ],
      "evidence": [
        {
          "ref": "source:docs/MASTER.md#L20",
          "kind": "document-heading",
          "fingerprint": "72fdb69e70ba18be"
        }
      ],
      "evidenceFingerprint": "e8e7cf9ab401fd78",
      "reusedFromPrevious": false
    },
    {
      "id": "functional-context:e1f00dde1db10807",
      "label": "참여자·접속 상태",
      "normalized": "참여자 접속 상태",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "source:src/components/ParticipantAvatar.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "9565fd5cde02b42f0b92"
        },
        {
          "ref": "source:src/components/ScopedParticipants.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "913a3f211bec0858f918"
        },
        {
          "ref": "source:src/lib/presence.js#L1",
          "kind": "feature-model",
          "fingerprint": "9595862c9f266b0953e6"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "262f689613b7ab62",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:a233b8099169d56e",
      "label": "초대·공유 진입",
      "normalized": "초대 공유 진입",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-subsystem",
        "ui-text"
      ],
      "evidence": [
        {
          "ref": "source:api/shared-canvas.js#L1",
          "kind": "feature-model",
          "fingerprint": "8ac0ed036a110f045ee7"
        },
        {
          "ref": "source:src/components/InvitePopover.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "7020afaf48a51283b8d3"
        },
        {
          "ref": "source:src/lib/shareLaunchCoordinator.js#L1",
          "kind": "feature-model",
          "fingerprint": "a9118d4ce77f8e9169dc"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        },
        {
          "ref": "source:src/App.jsx#L4802",
          "kind": "ui-text",
          "fingerprint": "e1b307140827f26542aa"
        },
        {
          "ref": "source:src/components/ScopedParticipants.jsx#L101",
          "kind": "ui-text",
          "fingerprint": "913a3f211bec0858f918"
        }
      ],
      "evidenceFingerprint": "0188978239822800",
      "reusedFromPrevious": false
    },
    {
      "id": "functional-context:73504474ad9e8f4c",
      "label": "캔버스 구조·동기화",
      "normalized": "캔버스 구조 동기화",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "profile-area"
      ],
      "evidence": [
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-area",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "6b9004bada23f364",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:5b15936a74d0917b",
      "label": "캔버스 상태·좌표",
      "normalized": "캔버스 상태 좌표",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "a5fbd7742403ede9",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:f31559e551a3a2cc",
      "label": "캔버스 작업 화면",
      "normalized": "캔버스 작업 화면",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "source:src/App.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "e1b307140827f26542aa"
        },
        {
          "ref": "source:src/components/CanvasTabs.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "5873ef7f7c009636aa87"
        },
        {
          "ref": "source:src/components/CodeWorldScreen.css#L1",
          "kind": "feature-model",
          "fingerprint": "c3a597bb6a6436e59a79"
        },
        {
          "ref": "source:src/components/CodeWorldScreen.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "63f8108a21f06d48f0dd"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "3bf7b751bb0d4542",
      "reusedFromPrevious": false
    },
    {
      "id": "functional-context:cd00237e7cb79723",
      "label": "캔버스 화면·편집",
      "normalized": "캔버스 화면 편집",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-area"
      ],
      "evidence": [
        {
          "ref": "source:src/App.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "e1b307140827f26542aa"
        },
        {
          "ref": "source:src/components/CanvasTabs.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "5873ef7f7c009636aa87"
        },
        {
          "ref": "source:src/components/CodeWorldScreen.css#L1",
          "kind": "feature-model",
          "fingerprint": "c3a597bb6a6436e59a79"
        },
        {
          "ref": "source:src/components/CodeWorldScreen.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "63f8108a21f06d48f0dd"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-area",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "153501c988bf4631",
      "reusedFromPrevious": false
    },
    {
      "id": "functional-context:7dee657ef47c4305",
      "label": "코드 구조·Git 동기화",
      "normalized": "코드 구조 git 동기화",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-area"
      ],
      "evidence": [
        {
          "ref": "source:api/local-connector.js#L1",
          "kind": "feature-model",
          "fingerprint": "8a8a2aef1fdc5fc57642"
        },
        {
          "ref": "source:api/source-twin-webhook.js#L1",
          "kind": "feature-model",
          "fingerprint": "ba21d0160c29a0d98a9b"
        },
        {
          "ref": "source:api/source-twin.js#L1",
          "kind": "feature-model",
          "fingerprint": "84e3d27ef435f909a13f"
        },
        {
          "ref": "source:mcp/localConnectorStore.js#L1",
          "kind": "feature-model",
          "fingerprint": "3615bf005d9857342fe8"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-area",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "b68e8a7fd86205f3",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:92c0b3681754b8d7",
      "label": "코드 구조·커넥터 검사",
      "normalized": "코드 구조 커넥터 검사",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "a5fbd7742403ede9",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:e2ff1ff664ec14b8",
      "label": "코드 발견·설명 생성",
      "normalized": "코드 발견 설명 생성",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "source:scripts/generate-source-twin.mjs#L1",
          "kind": "feature-model",
          "fingerprint": "60486ce5827d1487b62b"
        },
        {
          "ref": "source:scripts/source-edit-executor.mjs#L1",
          "kind": "feature-model",
          "fingerprint": "ea3f090c474db262a004"
        },
        {
          "ref": "source:scripts/source-lens-engine.mjs#L1",
          "kind": "feature-model",
          "fingerprint": "62505590959d295b4636"
        },
        {
          "ref": "source:scripts/source-profiles/fastapi-order-service.mjs#L1",
          "kind": "feature-model",
          "fingerprint": "fa5205272965f57d30ee"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "6dc386b90edf916f",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:6f93e5d6dfa2916c",
      "label": "코드 탐색·상태 이력",
      "normalized": "코드 탐색 상태 이력",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "source:api/source-twin.js#L1",
          "kind": "feature-model",
          "fingerprint": "84e3d27ef435f909a13f"
        },
        {
          "ref": "source:mcp/sourceTwinStore.js#L1",
          "kind": "feature-model",
          "fingerprint": "800ce7d5f9c6cbb99005"
        },
        {
          "ref": "source:shared/sourceTwin.js#L1",
          "kind": "feature-model",
          "fingerprint": "3f398e85e9381be27922"
        },
        {
          "ref": "source:src/components/SourceTwinPanel.jsx#L1",
          "kind": "feature-model",
          "fingerprint": "9c48cae2b232cc030120"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "d3b7291be3d517f9",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:adfff49f075c072b",
      "label": "클라우드 저장·실시간 동기화",
      "normalized": "클라우드 저장 실시간 동기화",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "profile-area",
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-area",
          "fingerprint": "0.9.0"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "55ea9b0d11f554f2",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:26293095b68aed8d",
      "label": "테스트·품질",
      "normalized": "테스트 품질",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "profile-area"
      ],
      "evidence": [
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-area",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "6b9004bada23f364",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:52a2819542f9e3b6",
      "label": "파일 저장·접근",
      "normalized": "파일 저장 접근",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "feature-model",
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "source:src/lib/imageStorage.js#L1",
          "kind": "feature-model",
          "fingerprint": "4c4da9626df402b048a8"
        },
        {
          "ref": "source:supabase-canvas-images.sql#L1",
          "kind": "feature-model",
          "fingerprint": "d9aafbd8cf7754ce4455"
        },
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "a49e7b9fd8d78e3b",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:1285187d7151a0e9",
      "label": "표준 용어집",
      "normalized": "표준 용어집",
      "confidence": "medium",
      "verification": "document-evidence",
      "sourceKinds": [
        "document-heading"
      ],
      "evidence": [
        {
          "ref": "source:docs/MASTER.md#L42",
          "kind": "document-heading",
          "fingerprint": "72fdb69e70ba18be"
        }
      ],
      "evidenceFingerprint": "0fc1c0cace702d6c",
      "reusedFromPrevious": false
    },
    {
      "id": "functional-context:eb7c7c192bcc02f0",
      "label": "프로젝트 기반·공통 규칙",
      "normalized": "프로젝트 기반 공통 규칙",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "profile-area"
      ],
      "evidence": [
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-area",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "6b9004bada23f364",
      "reusedFromPrevious": true
    },
    {
      "id": "functional-context:f568b84dd762cf32",
      "label": "프로젝트 설정·외부 라이브러리",
      "normalized": "프로젝트 설정 외부 라이브러리",
      "confidence": "high",
      "verification": "source-evidence",
      "sourceKinds": [
        "profile-subsystem"
      ],
      "evidence": [
        {
          "ref": "profile:workflow-canvas@0.9.0",
          "kind": "profile-subsystem",
          "fingerprint": "0.9.0"
        }
      ],
      "evidenceFingerprint": "a5fbd7742403ede9",
      "reusedFromPrevious": true
    }
  ],
  "diagnostics": [
    {
      "code": "functional-context-documents-possibly-stale",
      "severity": "attention",
      "message": "코드 근거가 바뀌었지만 그대로인 문서는 이번 기능 어휘 입력에서 제외했습니다.",
      "paths": [
        "README.md",
        "docs/README.md",
        "docs/product/PRODUCT_CATALOG.md",
        "docs/twin/README.md"
      ]
    }
  ],
  "summary": {
    "documents": 5,
    "usedDocuments": 1,
    "possiblyStaleDocuments": 4,
    "vocabularyTerms": 64,
    "sourceVerifiedTerms": 61,
    "reusedTerms": 51
  },
  "fingerprint": "3cd6aaa54b33f411",
  "reuse": {
    "previousPackFingerprint": "f4561f6518fe3a53",
    "reusedTerms": 51,
    "invalidatedTerms": 13
  }
}
)
