import { createTwinBuildFromCanvasTemplate } from './twinBuildCanvas.js'
import { extendWorkflowTwinBuildWithSourceFeatures } from './workflowSourceFeatureBuild.js'
import { TWIN_ENGINE_SCHEMA_VERSION } from './twinAdapterContract.js'
import { createWorkflowCanvasSystemMap } from './workflowCanvasSystemMap.js'
import { WORKFLOW_SYSTEM_DISCOVERY_SOURCE_ID } from './workflowSystemDiscovery.js'
import { WORKFLOW_SYSTEM_DISCOVERY } from './workflowSystemDiscoveryManifest.js'
import { WORKFLOW_SYSTEM_TWIN_ADAPTER_DESCRIPTOR } from './workflowSystemTwinAdapterDescriptor.js'
import {
  applyWorkflowTrustTopologyToCanvas,
  WORKFLOW_ACCESS_METADATA_CLASS_ID,
  WORKFLOW_CANVAS_CONTENT_CLASS_ID,
  WORKFLOW_IMAGE_CONTENT_CLASS_ID,
  WORKFLOW_PUBLIC_APP_ASSETS_CLASS_ID,
  WORKFLOW_SOURCE_CODE_CLASS_ID,
  WORKFLOW_TRUST_GATEWAYS,
  WORKFLOW_TRUST_TOPOLOGY_EVIDENCE_ID,
  WORKFLOW_TRUST_ZONES,
} from './workflowTrustTopology.js'
import {
  WORKFLOW_GIT_SYNC_AUDIT_CLASS_ID as GIT_SYNC_AUDIT_CLASS_ID,
  WORKFLOW_GIT_SYNC_CONTROL_EVIDENCE_ID as GIT_SYNC_CONTROL_EVIDENCE_ID,
  WORKFLOW_GIT_SYNC_EVIDENCE_ID as GIT_SYNC_EVIDENCE_ID,
  WORKFLOW_GIT_SYNC_LOCAL_POLICY_ID as GIT_SYNC_LOCAL_POLICY_ID,
  WORKFLOW_GIT_SYNC_OPERATION_DEFINITION,
  WORKFLOW_GIT_SYNC_OPERATION_ID as GIT_SYNC_OPERATION_ID,
  WORKFLOW_GIT_SYNC_OWNER_POLICY_ID as GIT_SYNC_OWNER_POLICY_ID,
  WORKFLOW_GIT_SYNC_POLICY_EVIDENCE_ID as GIT_SYNC_POLICY_EVIDENCE_ID,
  WORKFLOW_GIT_SYNC_STATE_CLASS_ID as GIT_SYNC_STATE_CLASS_ID,
  WORKFLOW_SOURCE_METADATA_CLASS_ID,
  WORKFLOW_SOURCE_SNAPSHOT_EVIDENCE_ID,
  WORKFLOW_SOURCE_SNAPSHOT_OPERATION_DEFINITION,
  WORKFLOW_SOURCE_SNAPSHOT_OPERATION_ID,
  WORKFLOW_SOURCE_SNAPSHOT_POLICY_ID,
} from './workflowOperationDefinitions.js'

function createWorkflowSystemTwinBuildResult() {
  const systemCanvas = applyWorkflowTrustTopologyToCanvas(createWorkflowCanvasSystemMap())
  const baseBuild = createTwinBuildFromCanvasTemplate({
    id: `workflow-system-build:${WORKFLOW_SYSTEM_DISCOVERY.current.id}`,
    source: {
      id: WORKFLOW_SYSTEM_DISCOVERY_SOURCE_ID,
      adapterId: WORKFLOW_SYSTEM_TWIN_ADAPTER_DESCRIPTOR.id,
      adapterContractVersion: WORKFLOW_SYSTEM_TWIN_ADAPTER_DESCRIPTOR.contractVersion,
      adapterVersion: WORKFLOW_SYSTEM_TWIN_ADAPTER_DESCRIPTOR.adapterVersion,
      engineSchemaVersion: TWIN_ENGINE_SCHEMA_VERSION,
      snapshotId: WORKFLOW_SYSTEM_DISCOVERY.current.id,
      label: 'Workflow Canvas 시스템',
      systemKind: 'software-application',
      observationLevel: 'discovered',
      rootEntityId: 'map-group-experience',
    },
    canvas: systemCanvas,
    trustZones: WORKFLOW_TRUST_ZONES,
    gateways: WORKFLOW_TRUST_GATEWAYS,
    evidence: [{
      id: WORKFLOW_TRUST_TOPOLOGY_EVIDENCE_ID,
      kind: 'code',
      ref: 'shared/workflowTrustTopology.js, shared/trustTopology.js, shared/twinBuild.js',
      summary: '자기 지도의 신뢰영역, 경계 통로와 보안 오버레이 판정 근거',
      confidence: 'high',
    }, {
      id: GIT_SYNC_EVIDENCE_ID,
      kind: 'connector',
      ref: 'scripts/local-connector-agent.mjs, shared/localConnector.js',
      summary: '로컬 저장소와 GitHub의 검증된 방향성 동기화 조작 계약',
      confidence: 'high',
    }, {
      id: GIT_SYNC_POLICY_EVIDENCE_ID,
      kind: 'code',
      ref: 'api/local-connector.js, mcp/localConnectorStore.js, mcp/systemOperationPlan.js',
      summary: '소유자 웹 승인, 서명 계획, 최신 상태 재검사, 일회성 실행 대기열 정책',
      confidence: 'high',
    }, {
      id: GIT_SYNC_CONTROL_EVIDENCE_ID,
      kind: 'code',
      ref: 'scripts/local-connector-agent.mjs:executeApprovedGitSync',
      summary: '고정 GitHub origin, 일반 push, fast-forward pull, 로컬 터미널 재승인 통제',
      confidence: 'high',
    }, {
      id: WORKFLOW_SOURCE_SNAPSHOT_EVIDENCE_ID,
      kind: 'code',
      ref: 'mcp/sourceTwinStore.js, supabase-source-twin-history.sql',
      summary: '제한된 시스템 메타데이터를 원자적 append-only 스냅샷과 감사 기록으로 생성하는 조작',
      confidence: 'high',
    }],
    dataClasses: [{
      id: GIT_SYNC_STATE_CLASS_ID,
      label: 'Git 구조·상태 메타데이터',
      description: '브랜치, 커밋 지문, ahead/behind, 변경 파일 경로처럼 동기화 판단에 필요한 메타데이터',
      sensitivity: 'internal',
      contentScope: 'metadata',
      retention: 'persistent',
      evidenceIds: [GIT_SYNC_EVIDENCE_ID],
    }, {
      id: GIT_SYNC_AUDIT_CLASS_ID,
      label: '조작 감사 메타데이터',
      description: '조작 ID, 상태 전이, 결과 지문과 제한된 실행 요약',
      sensitivity: 'internal',
      contentScope: 'metadata',
      retention: 'persistent',
      evidenceIds: [GIT_SYNC_POLICY_EVIDENCE_ID],
    }, {
      id: WORKFLOW_SOURCE_METADATA_CLASS_ID,
      label: '시스템 소스·배포 메타데이터',
      description: '파일·자원 이름과 지문, DB 선언, 배포 리비전, 집계 운영 상태처럼 본문을 제외한 시스템 정보',
      sensitivity: 'internal',
      contentScope: 'metadata',
      retention: 'persistent',
      evidenceIds: [WORKFLOW_SOURCE_SNAPSHOT_EVIDENCE_ID],
    }, {
      id: WORKFLOW_PUBLIC_APP_ASSETS_CLASS_ID,
      label: '공개 웹 앱 자원',
      description: '브라우저에 전달되는 HTML, JavaScript, CSS와 공개 정적 자원',
      sensitivity: 'public',
      contentScope: 'content',
      retention: 'persistent',
      evidenceIds: [WORKFLOW_TRUST_TOPOLOGY_EVIDENCE_ID],
    }, {
      id: WORKFLOW_CANVAS_CONTENT_CLASS_ID,
      label: '사용자 캔버스 문서',
      description: '사용자가 작성한 노드, 연결선, 노트, 이미지 참조와 저장 뷰 본문',
      sensitivity: 'sensitive',
      contentScope: 'content',
      retention: 'persistent',
      evidenceIds: [WORKFLOW_TRUST_TOPOLOGY_EVIDENCE_ID],
    }, {
      id: WORKFLOW_ACCESS_METADATA_CLASS_ID,
      label: '신원·공유 권한 메타데이터',
      description: '사용자 식별자, 세션 참조, 공유 범위, 역할과 리비전 정보',
      sensitivity: 'restricted',
      contentScope: 'metadata',
      retention: 'persistent',
      evidenceIds: [WORKFLOW_TRUST_TOPOLOGY_EVIDENCE_ID],
    }, {
      id: WORKFLOW_IMAGE_CONTENT_CLASS_ID,
      label: '캔버스 이미지 본문',
      description: '비공개 Storage 버킷에 저장되는 사용자의 캔버스 이미지 파일',
      sensitivity: 'sensitive',
      contentScope: 'content',
      retention: 'persistent',
      evidenceIds: [WORKFLOW_TRUST_TOPOLOGY_EVIDENCE_ID],
    }, {
      id: WORKFLOW_SOURCE_CODE_CLASS_ID,
      label: '제품 소스 코드',
      description: '허용된 로컬 저장소와 GitHub 원격 사이에서 동기화되는 버전 관리 소스',
      sensitivity: 'internal',
      contentScope: 'content',
      retention: 'persistent',
      evidenceIds: [WORKFLOW_TRUST_TOPOLOGY_EVIDENCE_ID],
    }],
    policies: [{
      id: GIT_SYNC_OWNER_POLICY_ID,
      kind: 'approval',
      label: '소유자 미리보기·명시 승인',
      description: '로그인한 커넥터 소유자가 최신 계획과 동기화 방향을 확인하고 승인해야 합니다.',
      effect: 'require_approval',
      subjects: ['authenticated-connector-owner'],
      actions: ['workflow.local.git-sync'],
      target: { kind: 'operation', id: GIT_SYNC_OPERATION_ID },
      enforcement: 'server',
      dataClassIds: [GIT_SYNC_STATE_CLASS_ID],
      evidenceIds: [GIT_SYNC_POLICY_EVIDENCE_ID],
    }, {
      id: GIT_SYNC_LOCAL_POLICY_ID,
      kind: 'approval',
      label: '로컬 터미널 재승인',
      description: '웹 승인과 별개로 허용된 저장소의 로컬 터미널에서 일회성 확인 문구를 입력해야 합니다.',
      effect: 'require_approval',
      subjects: ['local-device-operator'],
      actions: ['workflow.local.git-sync'],
      target: { kind: 'operation', id: GIT_SYNC_OPERATION_ID },
      enforcement: 'connector',
      dataClassIds: [GIT_SYNC_STATE_CLASS_ID],
      evidenceIds: [GIT_SYNC_CONTROL_EVIDENCE_ID],
    }, {
      id: WORKFLOW_SOURCE_SNAPSHOT_POLICY_ID,
      kind: 'approval',
      label: '제품 소유자 스냅샷 승인',
      description: '현재 시스템 상태와 기록 범위를 미리 본 제품 소유자만 불변 스냅샷 생성을 승인합니다.',
      effect: 'require_approval',
      subjects: ['workflow-product-owner'],
      actions: ['source-twin.snapshot.create'],
      target: { kind: 'operation', id: WORKFLOW_SOURCE_SNAPSHOT_OPERATION_ID },
      enforcement: 'server',
      dataClassIds: [WORKFLOW_SOURCE_METADATA_CLASS_ID, GIT_SYNC_AUDIT_CLASS_ID],
      evidenceIds: [WORKFLOW_SOURCE_SNAPSHOT_EVIDENCE_ID],
    }],
    operations: [WORKFLOW_GIT_SYNC_OPERATION_DEFINITION, WORKFLOW_SOURCE_SNAPSHOT_OPERATION_DEFINITION],
    observations: [{
      id: 'observation:workflow-git-sync-contract',
      kind: 'execution',
      label: 'Git 동기화 실행 계약 발견',
      subject: { kind: 'operation', id: GIT_SYNC_OPERATION_ID },
      reality: 'discovered',
      status: 'executable',
      summary: '코드에서 미리보기, 이중 승인, 상태 재검사, 제한 실행과 감사 기록 경로를 발견했습니다.',
      dataClassIds: [GIT_SYNC_STATE_CLASS_ID, GIT_SYNC_AUDIT_CLASS_ID],
      evidenceIds: [GIT_SYNC_POLICY_EVIDENCE_ID, GIT_SYNC_CONTROL_EVIDENCE_ID],
    }, {
      id: 'observation:workflow-source-snapshot-contract',
      kind: 'execution',
      label: '불변 스냅샷 실행 계약 발견',
      subject: { kind: 'operation', id: WORKFLOW_SOURCE_SNAPSHOT_OPERATION_ID },
      reality: 'discovered',
      status: 'executable',
      summary: '서명 계획, 상태 재검사, 원자적 생성, 결과 대조와 감사 기록 경로를 발견했습니다.',
      dataClassIds: [WORKFLOW_SOURCE_METADATA_CLASS_ID, GIT_SYNC_AUDIT_CLASS_ID],
      evidenceIds: [WORKFLOW_SOURCE_SNAPSHOT_EVIDENCE_ID],
    }],
    controls: [{
      id: 'control:workflow-git-sync-command-allowlist',
      kind: 'validation',
      label: 'Git 명령 허용 목록',
      description: '일반 push와 fast-forward merge 이외의 임의 셸·강제 push·자동 커밋을 실행하지 않습니다.',
      effect: 'prevent',
      status: 'verified',
      target: { kind: 'operation', id: GIT_SYNC_OPERATION_ID },
      policyIds: [GIT_SYNC_LOCAL_POLICY_ID],
      evidenceIds: [GIT_SYNC_CONTROL_EVIDENCE_ID],
    }, {
      id: 'control:workflow-git-sync-state-revalidation',
      kind: 'validation',
      label: '실행 직전 상태 재검사',
      description: '승인 뒤 브랜치, 커밋, origin 또는 작업 트리 상태가 바뀌면 실행을 중단합니다.',
      effect: 'prevent',
      status: 'verified',
      target: { kind: 'operation', id: GIT_SYNC_OPERATION_ID },
      policyIds: [GIT_SYNC_OWNER_POLICY_ID, GIT_SYNC_LOCAL_POLICY_ID],
      evidenceIds: [GIT_SYNC_POLICY_EVIDENCE_ID, GIT_SYNC_CONTROL_EVIDENCE_ID],
    }, {
      id: 'control:workflow-source-snapshot-redaction',
      kind: 'validation',
      label: '스냅샷 본문·자격증명 제외',
      description: '소스 본문, 캔버스 본문, 사용자 이메일과 실제 자격증명 값을 쓰기 범위에서 제외합니다.',
      effect: 'prevent',
      status: 'verified',
      target: { kind: 'operation', id: WORKFLOW_SOURCE_SNAPSHOT_OPERATION_ID },
      policyIds: [WORKFLOW_SOURCE_SNAPSHOT_POLICY_ID],
      evidenceIds: [WORKFLOW_SOURCE_SNAPSHOT_EVIDENCE_ID],
    }],
    threats: [{
      id: 'threat:workflow-git-sync-origin-substitution',
      label: '승인 후 Git 원격 바꿔치기',
      description: '웹 승인 뒤 로컬 origin을 다른 저장소로 바꿔 코드나 메타데이터를 의도하지 않은 원격으로 보낼 수 있는 잠재 경로입니다.',
      category: 'exfiltration',
      status: 'mitigated',
      likelihood: 'low',
      impact: 'high',
      source: { kind: 'entity', id: 'map-local-repo' },
      target: { kind: 'entity', id: 'map-github' },
      dataClassIds: [GIT_SYNC_STATE_CLASS_ID],
      controlIds: ['control:workflow-git-sync-command-allowlist', 'control:workflow-git-sync-state-revalidation'],
      evidenceIds: [GIT_SYNC_CONTROL_EVIDENCE_ID],
    }],
  })
  return extendWorkflowTwinBuildWithSourceFeatures(baseBuild)
}

const WORKFLOW_SYSTEM_TWIN_BUILD_RESULT = createWorkflowSystemTwinBuildResult()

export function createWorkflowSystemTwinBuild() {
  return createWorkflowSystemTwinBuildResult().build
}

export const WORKFLOW_SYSTEM_TWIN_BUILD = WORKFLOW_SYSTEM_TWIN_BUILD_RESULT.build
export const WORKFLOW_SOURCE_FEATURE_EXTENSION = WORKFLOW_SYSTEM_TWIN_BUILD_RESULT.extension
