import { createTwinBuildFromCanvasTemplate } from './twinBuildCanvas.js'
import { extendWorkflowTwinBuildWithSourceFeatures } from './workflowSourceFeatureBuild.js'
import { TWIN_ENGINE_SCHEMA_VERSION } from './twinAdapterContract.js'
import { createWorkflowCanvasSystemMap } from './workflowCanvasSystemMap.js'
import { WORKFLOW_SYSTEM_DISCOVERY_SOURCE_ID } from './workflowSystemDiscovery.js'
import { WORKFLOW_SYSTEM_DISCOVERY } from './workflowSystemDiscoveryManifest.js'
import { WORKFLOW_SYSTEM_TWIN_ADAPTER_DESCRIPTOR } from './workflowSystemTwinAdapterDescriptor.js'
import {
  applyWorkflowTrustTopologyToCanvas,
  WORKFLOW_ACCESS_METADATA_CLASS_ID,
  WORKFLOW_CANVAS_CONTENT_CLASS_ID,
  WORKFLOW_IMAGE_CONTENT_CLASS_ID,
  WORKFLOW_PUBLIC_APP_ASSETS_CLASS_ID,
  WORKFLOW_SOURCE_AI_EXPLANATION_INPUT_CLASS_ID,
  WORKFLOW_SOURCE_CODE_CLASS_ID,
  WORKFLOW_TRUST_GATEWAYS,
  WORKFLOW_TRUST_TOPOLOGY_EVIDENCE_ID,
  WORKFLOW_TRUST_ZONES,
} from './workflowTrustTopology.js'
import {
  WORKFLOW_GIT_SYNC_AUDIT_CLASS_ID as GIT_SYNC_AUDIT_CLASS_ID,
  WORKFLOW_GIT_SYNC_CONTROL_EVIDENCE_ID as GIT_SYNC_CONTROL_EVIDENCE_ID,
  WORKFLOW_GIT_SYNC_EVIDENCE_ID as GIT_SYNC_EVIDENCE_ID,
  WORKFLOW_GIT_SYNC_LOCAL_POLICY_ID as GIT_SYNC_LOCAL_POLICY_ID,
  WORKFLOW_GIT_SYNC_OPERATION_DEFINITION,
  WORKFLOW_GIT_SYNC_OPERATION_ID as GIT_SYNC_OPERATION_ID,
  WORKFLOW_GIT_SYNC_OWNER_POLICY_ID as GIT_SYNC_OWNER_POLICY_ID,
  WORKFLOW_GIT_SYNC_POLICY_EVIDENCE_ID as GIT_SYNC_POLICY_EVIDENCE_ID,
  WORKFLOW_GIT_SYNC_STATE_CLASS_ID as GIT_SYNC_STATE_CLASS_ID,
  WORKFLOW_SOURCE_METADATA_CLASS_ID,
  WORKFLOW_SOURCE_EDIT_CONTROL_EVIDENCE_ID,
  WORKFLOW_SOURCE_EDIT_EVIDENCE_ID,
  WORKFLOW_SOURCE_EDIT_INPUT_CLASS_ID,
  WORKFLOW_SOURCE_EDIT_LOCAL_POLICY_ID,
  WORKFLOW_SOURCE_EDIT_OPERATION_DEFINITION,
  WORKFLOW_SOURCE_EDIT_OPERATION_ID,
  WORKFLOW_SOURCE_EDIT_OWNER_POLICY_ID,
  WORKFLOW_SOURCE_EDIT_POLICY_EVIDENCE_ID,
  WORKFLOW_SOURCE_EDIT_ROLLBACK_LOCAL_POLICY_ID,
  WORKFLOW_SOURCE_EDIT_ROLLBACK_OPERATION_DEFINITION,
  WORKFLOW_SOURCE_EDIT_ROLLBACK_OPERATION_ID,
  WORKFLOW_SOURCE_EDIT_ROLLBACK_OWNER_POLICY_ID,
  WORKFLOW_SOURCE_SNAPSHOT_EVIDENCE_ID,
  WORKFLOW_SOURCE_SNAPSHOT_OPERATION_DEFINITION,
  WORKFLOW_SOURCE_SNAPSHOT_OPERATION_ID,
  WORKFLOW_SOURCE_SNAPSHOT_POLICY_ID,
} from './workflowOperationDefinitions.js'

function createWorkflowSystemTwinBuildResult() {
  const systemCanvas = applyWorkflowTrustTopologyToCanvas(createWorkflowCanvasSystemMap())
  const baseBuild = createTwinBuildFromCanvasTemplate({
    id: `workflow-system-build:${WORKFLOW_SYSTEM_DISCOVERY.current.id}`,
    source: {
      id: WORKFLOW_SYSTEM_DISCOVERY_SOURCE_ID,
      adapterId: WORKFLOW_SYSTEM_TWIN_ADAPTER_DESCRIPTOR.id,
      adapterContractVersion: WORKFLOW_SYSTEM_TWIN_ADAPTER_DESCRIPTOR.contractVersion,
      adapterVersion: WORKFLOW_SYSTEM_TWIN_ADAPTER_DESCRIPTOR.adapterVersion,
      engineSchemaVersion: TWIN_ENGINE_SCHEMA_VERSION,
      snapshotId: WORKFLOW_SYSTEM_DISCOVERY.current.id,
      label: 'Workflow Canvas 시스템',
      systemKind: 'software-application',
      observationLevel: 'discovered',
      rootEntityId: 'map-group-experience',
    },
    canvas: systemCanvas,
    trustZones: WORKFLOW_TRUST_ZONES,
    gateways: WORKFLOW_TRUST_GATEWAYS,
    evidence: [{
      id: WORKFLOW_TRUST_TOPOLOGY_EVIDENCE_ID,
      kind: 'code',
      ref: 'shared/workflowTrustTopology.js, shared/trustTopology.js, shared/twinBuild.js',
      summary: '자기 지도의 신뢰영역, 경계 통로와 보안 오버레이 판정 근거',
      confidence: 'high',
    }, {
      id: GIT_SYNC_EVIDENCE_ID,
      kind: 'connector',
      ref: 'scripts/local-connector-agent.mjs, shared/localConnector.js',
      summary: '로컬 저장소와 GitHub의 검증된 방향성 동기화 조작 계약',
      confidence: 'high',
    }, {
      id: GIT_SYNC_POLICY_EVIDENCE_ID,
      kind: 'code',
      ref: 'api/local-connector.js, mcp/localConnectorStore.js, mcp/systemOperationPlan.js',
      summary: '소유자 웹 승인, 서명 계획, 최신 상태 재검사, 일회성 실행 대기열 정책',
      confidence: 'high',
    }, {
      id: GIT_SYNC_CONTROL_EVIDENCE_ID,
      kind: 'code',
      ref: 'scripts/local-connector-agent.mjs:executeApprovedGitSync',
      summary: '고정 GitHub origin, 일반 push, fast-forward pull, 로컬 터미널 재승인 통제',
      confidence: 'high',
    }, {
      id: WORKFLOW_SOURCE_SNAPSHOT_EVIDENCE_ID,
      kind: 'code',
      ref: 'mcp/sourceTwinStore.js, supabase-source-twin-history.sql',
      summary: '제한된 시스템 메타데이터를 원자적 append-only 스냅샷과 감사 기록으로 생성하는 조작',
      confidence: 'high',
    }, {
      id: WORKFLOW_SOURCE_EDIT_EVIDENCE_ID,
      kind: 'code',
      ref: 'shared/sourceEditableProperties.js, shared/workflowSourceEditableProperties.js, scripts/source-edit-executor.mjs',
      summary: '명시적으로 등록된 UI literal만 AST 앵커로 찾아 타입·범위를 검증하는 왕복 편집 계약',
      confidence: 'high',
    }, {
      id: WORKFLOW_SOURCE_EDIT_POLICY_EVIDENCE_ID,
      kind: 'code',
      ref: 'api/source-twin.js, mcp/localConnectorStore.js, mcp/systemOperationPlan.js',
      summary: '소유자 전용 미리보기, 서명 계획, 최신 상태 재검사와 일회성 실행 대기열 정책',
      confidence: 'high',
    }, {
      id: WORKFLOW_SOURCE_EDIT_CONTROL_EVIDENCE_ID,
      kind: 'code',
      ref: 'scripts/local-connector-agent.mjs, scripts/test-source-editable-properties.mjs',
      summary: '격리 worktree, 정확한 diff, 테스트·빌드, 로컬 터미널 재승인과 provenance 커밋 통제',
      confidence: 'high',
    }],
    dataClasses: [{
      id: GIT_SYNC_STATE_CLASS_ID,
      label: 'Git 구조·상태 메타데이터',
      description: '브랜치, 커밋 지문, ahead/behind, 변경 파일 경로처럼 동기화 판단에 필요한 메타데이터',
      sensitivity: 'internal',
      contentScope: 'metadata',
      retention: 'persistent',
      evidenceIds: [GIT_SYNC_EVIDENCE_ID],
    }, {
      id: GIT_SYNC_AUDIT_CLASS_ID,
      label: '조작 감사 메타데이터',
      description: '조작 ID, 상태 전이, 결과 지문과 제한된 실행 요약',
      sensitivity: 'internal',
      contentScope: 'metadata',
      retention: 'persistent',
      evidenceIds: [GIT_SYNC_POLICY_EVIDENCE_ID],
    }, {
      id: WORKFLOW_SOURCE_METADATA_CLASS_ID,
      label: '시스템 소스·배포 메타데이터',
      description: '파일·자원 이름과 지문, DB 선언, 배포 리비전, 집계 운영 상태처럼 본문을 제외한 시스템 정보',
      sensitivity: 'internal',
      contentScope: 'metadata',
      retention: 'persistent',
      evidenceIds: [WORKFLOW_SOURCE_SNAPSHOT_EVIDENCE_ID],
    }, {
      id: WORKFLOW_SOURCE_AI_EXPLANATION_INPUT_CLASS_ID,
      label: 'AI 설명용 제한 코드 메타데이터',
      description: '코드 파츠 종류, 심볼, 상대 경로, 줄 범위, AST 종류와 결정적 요약만 포함하며 코드 본문·캔버스·키 값은 제외',
      sensitivity: 'internal',
      contentScope: 'metadata',
      retention: 'transient',
      evidenceIds: [WORKFLOW_TRUST_TOPOLOGY_EVIDENCE_ID],
    }, {
      id: WORKFLOW_SOURCE_EDIT_INPUT_CLASS_ID,
      label: '등록 UI 속성 편집 계획',
      description: '등록 속성 ID, 타입 검증된 이전·요청 값, AST 앵커와 상태 지문으로 이루어진 일회성 조작 입력',
      sensitivity: 'internal',
      contentScope: 'content',
      retention: 'transient',
      evidenceIds: [WORKFLOW_SOURCE_EDIT_EVIDENCE_ID, WORKFLOW_SOURCE_EDIT_POLICY_EVIDENCE_ID],
    }, {
      id: WORKFLOW_PUBLIC_APP_ASSETS_CLASS_ID,
      label: '공개 웹 앱 자원',
      description: '브라우저에 전달되는 HTML, JavaScript, CSS와 공개 정적 자원',
      sensitivity: 'public',
      contentScope: 'content',
      retention: 'persistent',
      evidenceIds: [WORKFLOW_TRUST_TOPOLOGY_EVIDENCE_ID],
    }, {
      id: WORKFLOW_CANVAS_CONTENT_CLASS_ID,
      label: '사용자 캔버스 문서',
      description: '사용자가 작성한 노드, 연결선, 노트, 이미지 참조와 저장 뷰 본문',
      sensitivity: 'sensitive',
      contentScope: 'content',
      retention: 'persistent',
      evidenceIds: [WORKFLOW_TRUST_TOPOLOGY_EVIDENCE_ID],
    }, {
      id: WORKFLOW_ACCESS_METADATA_CLASS_ID,
      label: '신원·공유 권한 메타데이터',
      description: '사용자 식별자, 세션 참조, 공유 범위, 역할과 리비전 정보',
      sensitivity: 'restricted',
      contentScope: 'metadata',
      retention: 'persistent',
      evidenceIds: [WORKFLOW_TRUST_TOPOLOGY_EVIDENCE_ID],
    }, {
      id: WORKFLOW_IMAGE_CONTENT_CLASS_ID,
      label: '캔버스 이미지 본문',
      description: '비공개 Storage 버킷에 저장되는 사용자의 캔버스 이미지 파일',
      sensitivity: 'sensitive',
      contentScope: 'content',
      retention: 'persistent',
      evidenceIds: [WORKFLOW_TRUST_TOPOLOGY_EVIDENCE_ID],
    }, {
      id: WORKFLOW_SOURCE_CODE_CLASS_ID,
      label: '제품 소스 코드',
      description: '허용된 로컬 저장소와 GitHub 원격 사이에서 동기화되는 버전 관리 소스',
      sensitivity: 'internal',
      contentScope: 'content',
      retention: 'persistent',
      evidenceIds: [WORKFLOW_TRUST_TOPOLOGY_EVIDENCE_ID],
    }],
    policies: [{
      id: GIT_SYNC_OWNER_POLICY_ID,
      kind: 'approval',
      label: '소유자 미리보기·명시 승인',
      description: '로그인한 커넥터 소유자가 최신 계획과 동기화 방향을 확인하고 승인해야 합니다.',
      effect: 'require_approval',
      subjects: ['authenticated-connector-owner'],
      actions: ['workflow.local.git-sync'],
      target: { kind: 'operation', id: GIT_SYNC_OPERATION_ID },
      enforcement: 'server',
      dataClassIds: [GIT_SYNC_STATE_CLASS_ID],
      evidenceIds: [GIT_SYNC_POLICY_EVIDENCE_ID],
    }, {
      id: GIT_SYNC_LOCAL_POLICY_ID,
      kind: 'approval',
      label: '로컬 터미널 재승인',
      description: '웹 승인과 별개로 허용된 저장소의 로컬 터미널에서 일회성 확인 문구를 입력해야 합니다.',
      effect: 'require_approval',
      subjects: ['local-device-operator'],
      actions: ['workflow.local.git-sync'],
      target: { kind: 'operation', id: GIT_SYNC_OPERATION_ID },
      enforcement: 'connector',
      dataClassIds: [GIT_SYNC_STATE_CLASS_ID],
      evidenceIds: [GIT_SYNC_CONTROL_EVIDENCE_ID],
    }, {
      id: WORKFLOW_SOURCE_SNAPSHOT_POLICY_ID,
      kind: 'approval',
      label: '제품 소유자 스냅샷 승인',
      description: '현재 시스템 상태와 기록 범위를 미리 본 제품 소유자만 불변 스냅샷 생성을 승인합니다.',
      effect: 'require_approval',
      subjects: ['workflow-product-owner'],
      actions: ['source-twin.snapshot.create'],
      target: { kind: 'operation', id: WORKFLOW_SOURCE_SNAPSHOT_OPERATION_ID },
      enforcement: 'server',
      dataClassIds: [WORKFLOW_SOURCE_METADATA_CLASS_ID, GIT_SYNC_AUDIT_CLASS_ID],
      evidenceIds: [WORKFLOW_SOURCE_SNAPSHOT_EVIDENCE_ID],
    }, {
      id: WORKFLOW_SOURCE_EDIT_OWNER_POLICY_ID,
      kind: 'approval',
      label: '소유자 편집 미리보기·명시 승인',
      description: '자기 시스템 지도 소유자가 등록 속성, 이전 값, 요청 값과 영향 범위를 확인해야 합니다.',
      effect: 'require_approval',
      subjects: ['workflow-product-owner'],
      actions: ['workflow.source-lens.safe-roundtrip-edit'],
      target: { kind: 'operation', id: WORKFLOW_SOURCE_EDIT_OPERATION_ID },
      enforcement: 'server',
      dataClassIds: [WORKFLOW_SOURCE_EDIT_INPUT_CLASS_ID],
      evidenceIds: [WORKFLOW_SOURCE_EDIT_POLICY_EVIDENCE_ID],
    }, {
      id: WORKFLOW_SOURCE_EDIT_LOCAL_POLICY_ID,
      kind: 'approval',
      label: '로컬 편집 별도 동의·터미널 재승인',
      description: '읽기 기본 커넥터와 분리된 쓰기 허용 플래그와 정확한 diff를 본 로컬 사용자의 일회성 확인이 모두 필요합니다.',
      effect: 'require_approval',
      subjects: ['local-device-operator'],
      actions: ['workflow.source-lens.safe-roundtrip-edit'],
      target: { kind: 'operation', id: WORKFLOW_SOURCE_EDIT_OPERATION_ID },
      enforcement: 'connector',
      dataClassIds: [WORKFLOW_SOURCE_EDIT_INPUT_CLASS_ID],
      evidenceIds: [WORKFLOW_SOURCE_EDIT_CONTROL_EVIDENCE_ID],
    }, {
      id: WORKFLOW_SOURCE_EDIT_ROLLBACK_OWNER_POLICY_ID,
      kind: 'approval',
      label: '소유자 롤백 미리보기·명시 승인',
      description: '소유자가 정확한 원본 편집 조작과 복구될 값을 확인해야 합니다.',
      effect: 'require_approval',
      subjects: ['workflow-product-owner'],
      actions: ['workflow.source-lens.safe-roundtrip-rollback'],
      target: { kind: 'operation', id: WORKFLOW_SOURCE_EDIT_ROLLBACK_OPERATION_ID },
      enforcement: 'server',
      dataClassIds: [WORKFLOW_SOURCE_EDIT_INPUT_CLASS_ID],
      evidenceIds: [WORKFLOW_SOURCE_EDIT_POLICY_EVIDENCE_ID],
    }, {
      id: WORKFLOW_SOURCE_EDIT_ROLLBACK_LOCAL_POLICY_ID,
      kind: 'approval',
      label: '로컬 롤백 터미널 재승인',
      description: '웹 승인과 별개로 revert diff와 대상 커밋을 터미널에서 다시 확인합니다.',
      effect: 'require_approval',
      subjects: ['local-device-operator'],
      actions: ['workflow.source-lens.safe-roundtrip-rollback'],
      target: { kind: 'operation', id: WORKFLOW_SOURCE_EDIT_ROLLBACK_OPERATION_ID },
      enforcement: 'connector',
      dataClassIds: [WORKFLOW_SOURCE_EDIT_INPUT_CLASS_ID],
      evidenceIds: [WORKFLOW_SOURCE_EDIT_CONTROL_EVIDENCE_ID],
    }],
    operations: [
      WORKFLOW_GIT_SYNC_OPERATION_DEFINITION,
      WORKFLOW_SOURCE_SNAPSHOT_OPERATION_DEFINITION,
      WORKFLOW_SOURCE_EDIT_OPERATION_DEFINITION,
      WORKFLOW_SOURCE_EDIT_ROLLBACK_OPERATION_DEFINITION,
    ],
    observations: [{
      id: 'observation:workflow-git-sync-contract',
      kind: 'execution',
      label: 'Git 동기화 실행 계약 발견',
      subject: { kind: 'operation', id: GIT_SYNC_OPERATION_ID },
      reality: 'discovered',
      status: 'executable',
      summary: '코드에서 미리보기, 이중 승인, 상태 재검사, 제한 실행과 감사 기록 경로를 발견했습니다.',
      dataClassIds: [GIT_SYNC_STATE_CLASS_ID, GIT_SYNC_AUDIT_CLASS_ID],
      evidenceIds: [GIT_SYNC_POLICY_EVIDENCE_ID, GIT_SYNC_CONTROL_EVIDENCE_ID],
    }, {
      id: 'observation:workflow-source-snapshot-contract',
      kind: 'execution',
      label: '불변 스냅샷 실행 계약 발견',
      subject: { kind: 'operation', id: WORKFLOW_SOURCE_SNAPSHOT_OPERATION_ID },
      reality: 'discovered',
      status: 'executable',
      summary: '서명 계획, 상태 재검사, 원자적 생성, 결과 대조와 감사 기록 경로를 발견했습니다.',
      dataClassIds: [WORKFLOW_SOURCE_METADATA_CLASS_ID, GIT_SYNC_AUDIT_CLASS_ID],
      evidenceIds: [WORKFLOW_SOURCE_SNAPSHOT_EVIDENCE_ID],
    }, {
      id: 'observation:workflow-source-edit-contract',
      kind: 'execution',
      label: '등록 UI 속성 편집 계약 발견',
      subject: { kind: 'operation', id: WORKFLOW_SOURCE_EDIT_OPERATION_ID },
      reality: 'discovered',
      status: 'executable',
      summary: '정확한 AST 앵커, 격리 검증, 이중 승인, provenance 커밋 경로를 코드에서 발견했습니다.',
      dataClassIds: [WORKFLOW_SOURCE_EDIT_INPUT_CLASS_ID, GIT_SYNC_AUDIT_CLASS_ID],
      evidenceIds: [WORKFLOW_SOURCE_EDIT_EVIDENCE_ID, WORKFLOW_SOURCE_EDIT_CONTROL_EVIDENCE_ID],
    }, {
      id: 'observation:workflow-source-edit-rollback-contract',
      kind: 'execution',
      label: '편집 롤백 계약 발견',
      subject: { kind: 'operation', id: WORKFLOW_SOURCE_EDIT_ROLLBACK_OPERATION_ID },
      reality: 'discovered',
      status: 'executable',
      summary: 'Git 이력을 지우지 않고 별도 승인된 새 revert provenance 커밋으로 복구하는 경로를 발견했습니다.',
      dataClassIds: [WORKFLOW_SOURCE_EDIT_INPUT_CLASS_ID, GIT_SYNC_AUDIT_CLASS_ID],
      evidenceIds: [WORKFLOW_SOURCE_EDIT_EVIDENCE_ID, WORKFLOW_SOURCE_EDIT_CONTROL_EVIDENCE_ID],
    }],
    controls: [{
      id: 'control:workflow-git-sync-command-allowlist',
      kind: 'validation',
      label: 'Git 명령 허용 목록',
      description: '일반 push와 fast-forward merge 이외의 임의 셸·강제 push·자동 커밋을 실행하지 않습니다.',
      effect: 'prevent',
      status: 'verified',
      target: { kind: 'operation', id: GIT_SYNC_OPERATION_ID },
      policyIds: [GIT_SYNC_LOCAL_POLICY_ID],
      evidenceIds: [GIT_SYNC_CONTROL_EVIDENCE_ID],
    }, {
      id: 'control:workflow-git-sync-state-revalidation',
      kind: 'validation',
      label: '실행 직전 상태 재검사',
      description: '승인 뒤 브랜치, 커밋, origin 또는 작업 트리 상태가 바뀌면 실행을 중단합니다.',
      effect: 'prevent',
      status: 'verified',
      target: { kind: 'operation', id: GIT_SYNC_OPERATION_ID },
      policyIds: [GIT_SYNC_OWNER_POLICY_ID, GIT_SYNC_LOCAL_POLICY_ID],
      evidenceIds: [GIT_SYNC_POLICY_EVIDENCE_ID, GIT_SYNC_CONTROL_EVIDENCE_ID],
    }, {
      id: 'control:workflow-source-snapshot-redaction',
      kind: 'validation',
      label: '스냅샷 본문·자격증명 제외',
      description: '소스 본문, 캔버스 본문, 사용자 이메일과 실제 자격증명 값을 쓰기 범위에서 제외합니다.',
      effect: 'prevent',
      status: 'verified',
      target: { kind: 'operation', id: WORKFLOW_SOURCE_SNAPSHOT_OPERATION_ID },
      policyIds: [WORKFLOW_SOURCE_SNAPSHOT_POLICY_ID],
      evidenceIds: [WORKFLOW_SOURCE_SNAPSHOT_EVIDENCE_ID],
    }, {
      id: 'control:workflow-source-edit-registered-ast-allowlist',
      kind: 'validation',
      label: '등록 AST literal 허용 목록',
      description: '프로필에 명시된 상대 경로·export·타입·범위와 현재 값이 일치하는 literal 하나만 편집합니다.',
      effect: 'prevent',
      status: 'verified',
      target: { kind: 'operation', id: WORKFLOW_SOURCE_EDIT_OPERATION_ID },
      policyIds: [WORKFLOW_SOURCE_EDIT_OWNER_POLICY_ID, WORKFLOW_SOURCE_EDIT_LOCAL_POLICY_ID],
      evidenceIds: [WORKFLOW_SOURCE_EDIT_EVIDENCE_ID],
    }, {
      id: 'control:workflow-source-edit-isolated-validation',
      kind: 'validation',
      label: '격리 검증·정확한 diff·이중 승인',
      description: '임시 worktree에서 편집하고 속성 검사, production build, diff 검사를 통과한 후 웹과 로컬 터미널에서 각각 승인합니다.',
      effect: 'prevent',
      status: 'verified',
      target: { kind: 'operation', id: WORKFLOW_SOURCE_EDIT_OPERATION_ID },
      policyIds: [WORKFLOW_SOURCE_EDIT_OWNER_POLICY_ID, WORKFLOW_SOURCE_EDIT_LOCAL_POLICY_ID],
      evidenceIds: [WORKFLOW_SOURCE_EDIT_POLICY_EVIDENCE_ID, WORKFLOW_SOURCE_EDIT_CONTROL_EVIDENCE_ID],
    }, {
      id: 'control:workflow-source-edit-no-history-rewrite',
      kind: 'recovery',
      label: '새 revert 커밋 복구',
      description: 'reset이나 이력 재작성 대신 원본 편집을 되돌리는 새 provenance 커밋을 만듭니다.',
      effect: 'recover',
      status: 'verified',
      target: { kind: 'operation', id: WORKFLOW_SOURCE_EDIT_ROLLBACK_OPERATION_ID },
      policyIds: [WORKFLOW_SOURCE_EDIT_ROLLBACK_OWNER_POLICY_ID, WORKFLOW_SOURCE_EDIT_ROLLBACK_LOCAL_POLICY_ID],
      evidenceIds: [WORKFLOW_SOURCE_EDIT_CONTROL_EVIDENCE_ID],
    }],
    threats: [{
      id: 'threat:workflow-git-sync-origin-substitution',
      label: '승인 후 Git 원격 바꿔치기',
      description: '웹 승인 뒤 로컬 origin을 다른 저장소로 바꿔 코드나 메타데이터를 의도하지 않은 원격으로 보낼 수 있는 잠재 경로입니다.',
      category: 'exfiltration',
      status: 'mitigated',
      likelihood: 'low',
      impact: 'high',
      source: { kind: 'entity', id: 'map-local-repo' },
      target: { kind: 'entity', id: 'map-github' },
      dataClassIds: [GIT_SYNC_STATE_CLASS_ID],
      controlIds: ['control:workflow-git-sync-command-allowlist', 'control:workflow-git-sync-state-revalidation'],
      evidenceIds: [GIT_SYNC_CONTROL_EVIDENCE_ID],
    }, {
      id: 'threat:workflow-source-edit-control-plane-compromise',
      label: '웹 제어 경로 탈취 후 로컬 편집 유도',
      description: '배포 서버나 소유자 세션이 탈취되어 조작 값을 조작해도 로컬 커넥터의 등록 속성 허용 목록과 터미널 diff 재승인을 넘어야 하는 잠재 경로입니다.',
      category: 'tampering',
      status: 'mitigated',
      likelihood: 'low',
      impact: 'high',
      source: { kind: 'entity', id: 'map-source-twin-api' },
      target: { kind: 'entity', id: 'map-local-repo' },
      dataClassIds: [WORKFLOW_SOURCE_EDIT_INPUT_CLASS_ID, WORKFLOW_SOURCE_CODE_CLASS_ID],
      controlIds: ['control:workflow-source-edit-registered-ast-allowlist', 'control:workflow-source-edit-isolated-validation'],
      evidenceIds: [WORKFLOW_SOURCE_EDIT_POLICY_EVIDENCE_ID, WORKFLOW_SOURCE_EDIT_CONTROL_EVIDENCE_ID],
    }],
  })
  return extendWorkflowTwinBuildWithSourceFeatures(baseBuild)
}

const WORKFLOW_SYSTEM_TWIN_BUILD_RESULT = createWorkflowSystemTwinBuildResult()

export function createWorkflowSystemTwinBuild() {
  return createWorkflowSystemTwinBuildResult().build
}

export const WORKFLOW_SYSTEM_TWIN_BUILD = WORKFLOW_SYSTEM_TWIN_BUILD_RESULT.build
export const WORKFLOW_SOURCE_FEATURE_EXTENSION = WORKFLOW_SYSTEM_TWIN_BUILD_RESULT.extension
